"""baseline schema

Revision ID: a94faba58104
Revises: 
Create Date: 2026-06-16 05:30:47.683432
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a94faba58104'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('accounting',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('proto', sa.String(length=8), nullable=False),
    sa.Column('ifname', sa.String(length=32), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('stopped_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('bytes_in', sa.BigInteger(), nullable=False),
    sa.Column('bytes_out', sa.BigInteger(), nullable=False),
    sa.Column('duration', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_accounting_stopped_at'), 'accounting', ['stopped_at'], unique=False)
    op.create_index(op.f('ix_accounting_username'), 'accounting', ['username'], unique=False)
    op.create_table('admin_invites',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('can_create_users', sa.Boolean(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('used', sa.Boolean(), nullable=False),
    sa.Column('used_by', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admin_invites_token'), 'admin_invites', ['token'], unique=True)
    op.create_table('admins',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('can_create_users', sa.Boolean(), nullable=False),
    sa.Column('max_users', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('last_login', sa.DateTime(timezone=True), nullable=True),
    sa.Column('note', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_admins_username'), 'admins', ['username'], unique=True)
    op.create_table('app_settings',
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('value', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('key')
    )
    op.create_table('audit_log',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(length=128), nullable=False),
    sa.Column('action', sa.String(length=64), nullable=False),
    sa.Column('target', sa.String(length=128), nullable=False),
    sa.Column('detail', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_log_ts'), 'audit_log', ['ts'], unique=False)
    op.create_table('sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('ifname', sa.String(length=32), nullable=False),
    sa.Column('peer_ip', sa.String(length=64), nullable=False),
    sa.Column('pid', sa.Integer(), nullable=False),
    sa.Column('proto', sa.String(length=8), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_rx', sa.BigInteger(), nullable=False),
    sa.Column('last_tx', sa.BigInteger(), nullable=False),
    sa.Column('base_rx', sa.BigInteger(), nullable=False),
    sa.Column('base_tx', sa.BigInteger(), nullable=False),
    sa.Column('gone_polls', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sessions_ifname'), 'sessions', ['ifname'], unique=True)
    op.create_index(op.f('ix_sessions_username'), 'sessions', ['username'], unique=False)
    op.create_table('traffic_samples',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('online_count', sa.Integer(), nullable=False),
    sa.Column('rx_bps', sa.Integer(), nullable=False),
    sa.Column('tx_bps', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_traffic_samples_ts'), 'traffic_samples', ['ts'], unique=False)
    op.create_table('usage_samples',
    sa.Column('ts', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ifname', sa.String(length=32), nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('proto', sa.String(length=8), nullable=False),
    sa.Column('rx_bytes', sa.BigInteger(), nullable=False),
    sa.Column('tx_bytes', sa.BigInteger(), nullable=False),
    sa.Column('rx_rate_bps', sa.BigInteger(), nullable=False),
    sa.Column('tx_rate_bps', sa.BigInteger(), nullable=False),
    sa.PrimaryKeyConstraint('ts', 'ifname')
    )
    op.create_index(op.f('ix_usage_samples_username'), 'usage_samples', ['username'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('username', sa.String(length=128), nullable=False),
    sa.Column('password_hash', sa.String(length=256), nullable=False),
    sa.Column('quota_bytes', sa.BigInteger(), nullable=False),
    sa.Column('used_bytes', sa.BigInteger(), nullable=False),
    sa.Column('rate_up_kbps', sa.Integer(), nullable=False),
    sa.Column('rate_down_kbps', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.Column('total_sessions', sa.Integer(), nullable=False),
    sa.Column('note', sa.Text(), nullable=False),
    sa.Column('created_by_admin_id', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_created_by_admin_id'), 'users', ['created_by_admin_id'], unique=False)
    op.create_index(op.f('ix_users_username'), 'users', ['username'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_username'), table_name='users')
    op.drop_index(op.f('ix_users_created_by_admin_id'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_usage_samples_username'), table_name='usage_samples')
    op.drop_table('usage_samples')
    op.drop_index(op.f('ix_traffic_samples_ts'), table_name='traffic_samples')
    op.drop_table('traffic_samples')
    op.drop_index(op.f('ix_sessions_username'), table_name='sessions')
    op.drop_index(op.f('ix_sessions_ifname'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_index(op.f('ix_audit_log_ts'), table_name='audit_log')
    op.drop_table('audit_log')
    op.drop_table('app_settings')
    op.drop_index(op.f('ix_admins_username'), table_name='admins')
    op.drop_table('admins')
    op.drop_index(op.f('ix_admin_invites_token'), table_name='admin_invites')
    op.drop_table('admin_invites')
    op.drop_index(op.f('ix_accounting_username'), table_name='accounting')
    op.drop_index(op.f('ix_accounting_stopped_at'), table_name='accounting')
    op.drop_table('accounting')
    # ### end Alembic commands ###
