"""wg_peers wireguard

Revision ID: b84d6e6d0e7c
Revises: a94faba58104
Create Date: 2026-06-16 20:10:50.435862
"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b84d6e6d0e7c'
down_revision: Union[str, None] = 'a94faba58104'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('wg_peers',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('public_key', sa.String(length=64), nullable=False),
    sa.Column('private_key', sa.String(length=64), nullable=False),
    sa.Column('preshared_key', sa.String(length=64), nullable=False),
    sa.Column('address', sa.String(length=64), nullable=False),
    sa.Column('base_rx', sa.BigInteger(), nullable=False),
    sa.Column('base_tx', sa.BigInteger(), nullable=False),
    sa.Column('last_rx', sa.BigInteger(), nullable=False),
    sa.Column('last_tx', sa.BigInteger(), nullable=False),
    sa.Column('last_handshake', sa.DateTime(timezone=True), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('address')
    )
    op.create_index(op.f('ix_wg_peers_public_key'), 'wg_peers', ['public_key'], unique=True)
    op.create_index(op.f('ix_wg_peers_user_id'), 'wg_peers', ['user_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_wg_peers_user_id'), table_name='wg_peers')
    op.drop_index(op.f('ix_wg_peers_public_key'), table_name='wg_peers')
    op.drop_table('wg_peers')
    # ### end Alembic commands ###
