// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.21.12
// source: athena/node/v1/nodehub.proto

// Control-plane contract between the panel (hub) and a termination node.
//
// Two rules this file exists to enforce, both learned before it was written:
//
//  1. THE NODE DIALS OUT. The hub never connects to a node. A node may sit
//     behind NAT, change address, or have its IP burned and replaced; none of
//     that should require the hub to know how to reach it. One inbound port on
//     the hub, none on the node.
//
//  2. COUNTERS ON THE WIRE ARE ABSOLUTE, NEVER DELTAS. The hub keeps the
//     watermark and computes the difference itself. A resent report is then a
//     no-op instead of double-counting, and a dropped one heals on the next
//     report instead of losing traffic forever. This is the single most
//     important property of the protocol -- deltas over an unreliable link
//     silently corrupt billing.
//
// The stream is bidirectional from day one even though the hub only replies
// with acks today: Phase 2 adds commands (disconnect, sync users, quota
// credit) as new variants of HubMessage.payload, which old agents ignore and
// new ones handle. Fields are only ever added, never renumbered or reused.

package pb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	NodeHub_Connect_FullMethodName = "/athena.node.v1.NodeHub/Connect"
)

// NodeHubClient is the client API for NodeHub service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type NodeHubClient interface {
	// Opened once by the agent and held open. Reports flow up, commands down.
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, HubMessage], error)
}

type nodeHubClient struct {
	cc grpc.ClientConnInterface
}

func NewNodeHubClient(cc grpc.ClientConnInterface) NodeHubClient {
	return &nodeHubClient{cc}
}

func (c *nodeHubClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentMessage, HubMessage], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &NodeHub_ServiceDesc.Streams[0], NodeHub_Connect_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AgentMessage, HubMessage]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeHub_ConnectClient = grpc.BidiStreamingClient[AgentMessage, HubMessage]

// NodeHubServer is the server API for NodeHub service.
// All implementations must embed UnimplementedNodeHubServer
// for forward compatibility.
type NodeHubServer interface {
	// Opened once by the agent and held open. Reports flow up, commands down.
	Connect(grpc.BidiStreamingServer[AgentMessage, HubMessage]) error
	mustEmbedUnimplementedNodeHubServer()
}

// UnimplementedNodeHubServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedNodeHubServer struct{}

func (UnimplementedNodeHubServer) Connect(grpc.BidiStreamingServer[AgentMessage, HubMessage]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}
func (UnimplementedNodeHubServer) mustEmbedUnimplementedNodeHubServer() {}
func (UnimplementedNodeHubServer) testEmbeddedByValue()                 {}

// UnsafeNodeHubServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to NodeHubServer will
// result in compilation errors.
type UnsafeNodeHubServer interface {
	mustEmbedUnimplementedNodeHubServer()
}

func RegisterNodeHubServer(s grpc.ServiceRegistrar, srv NodeHubServer) {
	// If the following call pancis, it indicates UnimplementedNodeHubServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&NodeHub_ServiceDesc, srv)
}

func _NodeHub_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(NodeHubServer).Connect(&grpc.GenericServerStream[AgentMessage, HubMessage]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type NodeHub_ConnectServer = grpc.BidiStreamingServer[AgentMessage, HubMessage]

// NodeHub_ServiceDesc is the grpc.ServiceDesc for NodeHub service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var NodeHub_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "athena.node.v1.NodeHub",
	HandlerType: (*NodeHubServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _NodeHub_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "athena/node/v1/nodehub.proto",
}
