// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: athena/node/v1/nodehub.proto

// Control-plane contract between the panel (hub) and a termination node.
//
// Two rules this file exists to enforce, both learned before it was written:
//
//  1. THE NODE DIALS OUT. The hub never connects to a node. A node may sit
//     behind NAT, change address, or have its IP burned and replaced; none of
//     that should require the hub to know how to reach it. One inbound port on
//     the hub, none on the node.
//
//  2. COUNTERS ON THE WIRE ARE ABSOLUTE, NEVER DELTAS. The hub keeps the
//     watermark and computes the difference itself. A resent report is then a
//     no-op instead of double-counting, and a dropped one heals on the next
//     report instead of losing traffic forever. This is the single most
//     important property of the protocol -- deltas over an unreliable link
//     silently corrupt billing.
//
// The stream is bidirectional from day one even though the hub only replies
// with acks today: Phase 2 adds commands (disconnect, sync users, quota
// credit) as new variants of HubMessage.payload, which old agents ignore and
// new ones handle. Fields are only ever added, never renumbered or reused.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Report
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetReport() *Report {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Report); ok {
			return x.Report
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // exactly once, first
}

type AgentMessage_Report struct {
	Report *Report `protobuf:"bytes,2,opt,name=report,proto3,oneof"` // then periodically, forever
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Report) isAgentMessage_Payload() {}

type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-node shared secret. Also sent as gRPC metadata; carried here too so a
	// stream can be authenticated from its first frame regardless of transport.
	Token        string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AgentVersion string `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Bumped only on an incompatible change. The hub refuses a version it cannot
	// speak rather than silently misreading it.
	ProtocolVersion uint32 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Hostname        string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os              string `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Kernel          string `protobuf:"bytes,6,opt,name=kernel,proto3" json:"kernel,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

type Report struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SentAtUnixMs  int64                  `protobuf:"varint,1,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	Host          *Host                  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Ppp           []*PppSession          `protobuf:"bytes,3,rep,name=ppp,proto3" json:"ppp,omitempty"`
	Wg            []*WgPeer              `protobuf:"bytes,4,rep,name=wg,proto3" json:"wg,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{2}
}

func (x *Report) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

func (x *Report) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Report) GetPpp() []*PppSession {
	if x != nil {
		return x.Ppp
	}
	return nil
}

func (x *Report) GetWg() []*WgPeer {
	if x != nil {
		return x.Wg
	}
	return nil
}

type Host struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds     uint64                 `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Load1             float64                `protobuf:"fixed64,2,opt,name=load1,proto3" json:"load1,omitempty"`
	MemTotalBytes     uint64                 `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	MemAvailableBytes uint64                 `protobuf:"varint,4,opt,name=mem_available_bytes,json=memAvailableBytes,proto3" json:"mem_available_bytes,omitempty"`
	// Whether the node's own VPN engines are alive. A node that reports but
	// whose engines are down is a different failure from one that is silent.
	Xl2TpdOk      bool `protobuf:"varint,5,opt,name=xl2tpd_ok,json=xl2tpdOk,proto3" json:"xl2tpd_ok,omitempty"`
	IpsecOk       bool `protobuf:"varint,6,opt,name=ipsec_ok,json=ipsecOk,proto3" json:"ipsec_ok,omitempty"`
	AccelPppOk    bool `protobuf:"varint,7,opt,name=accel_ppp_ok,json=accelPppOk,proto3" json:"accel_ppp_ok,omitempty"`
	WireguardOk   bool `protobuf:"varint,8,opt,name=wireguard_ok,json=wireguardOk,proto3" json:"wireguard_ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{3}
}

func (x *Host) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Host) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Host) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *Host) GetMemAvailableBytes() uint64 {
	if x != nil {
		return x.MemAvailableBytes
	}
	return 0
}

func (x *Host) GetXl2TpdOk() bool {
	if x != nil {
		return x.Xl2TpdOk
	}
	return false
}

func (x *Host) GetIpsecOk() bool {
	if x != nil {
		return x.IpsecOk
	}
	return false
}

func (x *Host) GetAccelPppOk() bool {
	if x != nil {
		return x.AccelPppOk
	}
	return false
}

func (x *Host) GetWireguardOk() bool {
	if x != nil {
		return x.WireguardOk
	}
	return false
}

// One live ppp interface. ABSOLUTE kernel counters since the interface came up.
type PppSession struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ifname  string                 `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
	RxBytes uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"` // from the client  (the user's upload)
	TxBytes uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"` // toward the client (the user's download)
	// Empty when the agent cannot map the interface to an account. The hub must
	// treat that as "unknown", never as "no user" -- silently dropping unmapped
	// traffic is how usage goes missing.
	Username      string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	PeerIp        string `protobuf:"bytes,5,opt,name=peer_ip,json=peerIp,proto3" json:"peer_ip,omitempty"`
	Pid           int32  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"` // meaningful ONLY on the node that reported it
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PppSession) Reset() {
	*x = PppSession{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PppSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PppSession) ProtoMessage() {}

func (x *PppSession) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PppSession.ProtoReflect.Descriptor instead.
func (*PppSession) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{4}
}

func (x *PppSession) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *PppSession) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *PppSession) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PppSession) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PppSession) GetPeerIp() string {
	if x != nil {
		return x.PeerIp
	}
	return ""
}

func (x *PppSession) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

// One WireGuard peer. ABSOLUTE counters since the peer was added.
type WgPeer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKey         string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	RxBytes           uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes           uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	LastHandshakeUnix int64                  `protobuf:"varint,4,opt,name=last_handshake_unix,json=lastHandshakeUnix,proto3" json:"last_handshake_unix,omitempty"` // 0 = never
	Address           string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WgPeer) Reset() {
	*x = WgPeer{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WgPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WgPeer) ProtoMessage() {}

func (x *WgPeer) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WgPeer.ProtoReflect.Descriptor instead.
func (*WgPeer) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{5}
}

func (x *WgPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WgPeer) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *WgPeer) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *WgPeer) GetLastHandshakeUnix() int64 {
	if x != nil {
		return x.LastHandshakeUnix
	}
	return 0
}

func (x *WgPeer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

type HubMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HubMessage_Welcome
	//	*HubMessage_Ack
	Payload       isHubMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubMessage) Reset() {
	*x = HubMessage{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessage) ProtoMessage() {}

func (x *HubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessage.ProtoReflect.Descriptor instead.
func (*HubMessage) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{6}
}

func (x *HubMessage) GetPayload() isHubMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HubMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *HubMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

type isHubMessage_Payload interface {
	isHubMessage_Payload()
}

type HubMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type HubMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

func (*HubMessage_Welcome) isHubMessage_Payload() {}

func (*HubMessage_Ack) isHubMessage_Payload() {}

type Welcome struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NodeId                int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName              string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ReportIntervalSeconds uint32                 `protobuf:"varint,3,opt,name=report_interval_seconds,json=reportIntervalSeconds,proto3" json:"report_interval_seconds,omitempty"`
	ProtocolVersion       uint32                 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{7}
}

func (x *Welcome) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Welcome) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Welcome) GetReportIntervalSeconds() uint32 {
	if x != nil {
		return x.ReportIntervalSeconds
	}
	return 0
}

func (x *Welcome) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

type Ack struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReceivedAtUnixMs int64                  `protobuf:"varint,1,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	Ok               bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail           string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{8}
}

func (x *Ack) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

var File_athena_node_v1_nodehub_proto protoreflect.FileDescriptor

var file_athena_node_v1_nodehub_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x22, 0x7a,
	0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x2d,
	0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15, 0x2e,
	0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x30, 0x0a,
	0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16, 0x2e,
	0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x52,
	0x65, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x42,
	0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xb1, 0x01, 0x0a, 0x05, 0x48,
	0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x67,
	0x65, 0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12,
	0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73,
	0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f,
	0x73, 0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x22, 0xaf,
	0x01, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a, 0x0f, 0x73, 0x65, 0x6e,
	0x74, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73,
	0x12, 0x28, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x14,
	0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x2c, 0x0a, 0x03, 0x70, 0x70,
	0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x70, 0x70, 0x53, 0x65, 0x73, 0x73,
	0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x70, 0x70, 0x12, 0x26, 0x0a, 0x02, 0x77, 0x67, 0x18, 0x04,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67, 0x50, 0x65, 0x65, 0x72, 0x52, 0x02, 0x77, 0x67,
	0x22, 0x98, 0x02, 0x0a, 0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x75, 0x70, 0x74,
	0x69, 0x6d, 0x65, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0d, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73,
	0x12, 0x14, 0x0a, 0x05, 0x6c, 0x6f, 0x61, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52,
	0x05, 0x6c, 0x6f, 0x61, 0x64, 0x31, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x65, 0x6d, 0x5f, 0x74, 0x6f,
	0x74, 0x61, 0x6c, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0d, 0x6d, 0x65, 0x6d, 0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2e,
	0x0a, 0x13, 0x6d, 0x65, 0x6d, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x6d, 0x65, 0x6d,
	0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1b,
	0x0a, 0x09, 0x78, 0x6c, 0x32, 0x74, 0x70, 0x64, 0x5f, 0x6f, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x08, 0x52, 0x08, 0x78, 0x6c, 0x32, 0x74, 0x70, 0x64, 0x4f, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x69,
	0x70, 0x73, 0x65, 0x63, 0x5f, 0x6f, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69,
	0x70, 0x73, 0x65, 0x63, 0x4f, 0x6b, 0x12, 0x20, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x6c, 0x5f,
	0x70, 0x70, 0x70, 0x5f, 0x6f, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x63,
	0x63, 0x65, 0x6c, 0x50, 0x70, 0x70, 0x4f, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x69, 0x72, 0x65,
	0x67, 0x75, 0x61, 0x72, 0x64, 0x5f, 0x6f, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b,
	0x77, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x4f, 0x6b, 0x22, 0xa1, 0x01, 0x0a, 0x0a,
	0x50, 0x70, 0x70, 0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61,
	0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x19, 0x0a,
	0x08, 0x74, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x74, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x70, 0x12, 0x10, 0x0a,
	0x03, 0x70, 0x69, 0x64, 0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x22,
	0xa7, 0x01, 0x0a, 0x06, 0x57, 0x67, 0x50, 0x65, 0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75,
	0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09,
	0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x78, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x72, 0x78, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x2e, 0x0a, 0x13, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b,
	0x65, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03, 0x52, 0x11, 0x6c, 0x61,
	0x73, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x55, 0x6e, 0x69, 0x78, 0x12,
	0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0x75, 0x0a, 0x0a, 0x48, 0x75, 0x62,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f,
	0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e,
	0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d,
	0x65, 0x48, 0x00, 0x52, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x27, 0x0a, 0x03,
	0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61, 0x74, 0x68, 0x65,
	0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x63, 0x6b, 0x48, 0x00,
	0x52, 0x03, 0x61, 0x63, 0x6b, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64,
	0x22, 0xa2, 0x01, 0x0a, 0x07, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e,
	0x6f, 0x64, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61,
	0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61,
	0x6d, 0x65, 0x12, 0x36, 0x0a, 0x17, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x74,
	0x65, 0x72, 0x76, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x15, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72,
	0x76, 0x61, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65,
	0x72, 0x73, 0x69, 0x6f, 0x6e, 0x22, 0x5c, 0x0a, 0x03, 0x41, 0x63, 0x6b, 0x12, 0x2d, 0x0a, 0x13,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78,
	0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10, 0x72, 0x65, 0x63, 0x65, 0x69,
	0x76, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73, 0x12, 0x0e, 0x0a, 0x02, 0x6f,
	0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b, 0x12, 0x16, 0x0a, 0x06, 0x64,
	0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x64, 0x65, 0x74,
	0x61, 0x69, 0x6c, 0x32, 0x52, 0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x75, 0x62, 0x12, 0x47,
	0x0a, 0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x2e, 0x61, 0x74, 0x68, 0x65,
	0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74,
	0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1a, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61,
	0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75,
	0x62, 0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x52, 0x4e, 0x30, 0x59, 0x2f, 0x41, 0x74, 0x68, 0x65,
	0x6e, 0x61, 0x50, 0x61, 0x6e, 0x65, 0x6c, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62,
	0x3b, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_athena_node_v1_nodehub_proto_rawDescOnce sync.Once
	file_athena_node_v1_nodehub_proto_rawDescData = file_athena_node_v1_nodehub_proto_rawDesc
)

func file_athena_node_v1_nodehub_proto_rawDescGZIP() []byte {
	file_athena_node_v1_nodehub_proto_rawDescOnce.Do(func() {
		file_athena_node_v1_nodehub_proto_rawDescData = protoimpl.X.CompressGZIP(file_athena_node_v1_nodehub_proto_rawDescData)
	})
	return file_athena_node_v1_nodehub_proto_rawDescData
}

var file_athena_node_v1_nodehub_proto_msgTypes = make([]protoimpl.MessageInfo, 9)
var file_athena_node_v1_nodehub_proto_goTypes = []any{
	(*AgentMessage)(nil), // 0: athena.node.v1.AgentMessage
	(*Hello)(nil),        // 1: athena.node.v1.Hello
	(*Report)(nil),       // 2: athena.node.v1.Report
	(*Host)(nil),         // 3: athena.node.v1.Host
	(*PppSession)(nil),   // 4: athena.node.v1.PppSession
	(*WgPeer)(nil),       // 5: athena.node.v1.WgPeer
	(*HubMessage)(nil),   // 6: athena.node.v1.HubMessage
	(*Welcome)(nil),      // 7: athena.node.v1.Welcome
	(*Ack)(nil),          // 8: athena.node.v1.Ack
}
var file_athena_node_v1_nodehub_proto_depIdxs = []int32{
	1, // 0: athena.node.v1.AgentMessage.hello:type_name -> athena.node.v1.Hello
	2, // 1: athena.node.v1.AgentMessage.report:type_name -> athena.node.v1.Report
	3, // 2: athena.node.v1.Report.host:type_name -> athena.node.v1.Host
	4, // 3: athena.node.v1.Report.ppp:type_name -> athena.node.v1.PppSession
	5, // 4: athena.node.v1.Report.wg:type_name -> athena.node.v1.WgPeer
	7, // 5: athena.node.v1.HubMessage.welcome:type_name -> athena.node.v1.Welcome
	8, // 6: athena.node.v1.HubMessage.ack:type_name -> athena.node.v1.Ack
	0, // 7: athena.node.v1.NodeHub.Connect:input_type -> athena.node.v1.AgentMessage
	6, // 8: athena.node.v1.NodeHub.Connect:output_type -> athena.node.v1.HubMessage
	8, // [8:9] is the sub-list for method output_type
	7, // [7:8] is the sub-list for method input_type
	7, // [7:7] is the sub-list for extension type_name
	7, // [7:7] is the sub-list for extension extendee
	0, // [0:7] is the sub-list for field type_name
}

func init() { file_athena_node_v1_nodehub_proto_init() }
func file_athena_node_v1_nodehub_proto_init() {
	if File_athena_node_v1_nodehub_proto != nil {
		return
	}
	file_athena_node_v1_nodehub_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Report)(nil),
	}
	file_athena_node_v1_nodehub_proto_msgTypes[6].OneofWrappers = []any{
		(*HubMessage_Welcome)(nil),
		(*HubMessage_Ack)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_athena_node_v1_nodehub_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   9,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_athena_node_v1_nodehub_proto_goTypes,
		DependencyIndexes: file_athena_node_v1_nodehub_proto_depIdxs,
		MessageInfos:      file_athena_node_v1_nodehub_proto_msgTypes,
	}.Build()
	File_athena_node_v1_nodehub_proto = out.File
	file_athena_node_v1_nodehub_proto_rawDesc = nil
	file_athena_node_v1_nodehub_proto_goTypes = nil
	file_athena_node_v1_nodehub_proto_depIdxs = nil
}
