// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.1
// 	protoc        v3.21.12
// source: athena/node/v1/nodehub.proto

// Control-plane contract between the panel (hub) and a termination node.
//
// ============================================================================
// THE FOUR RULES THIS FILE EXISTS TO ENFORCE
// ============================================================================
//
//  1. THE NODE DIALS OUT. The hub never connects to a node. A node may sit
//     behind NAT, change address, or have its IP burned and replaced; none of
//     that should require the hub to know how to reach it. One inbound port on
//     the hub, none on the node.
//
//  2. COUNTERS ON THE WIRE ARE ABSOLUTE, NEVER DELTAS. The hub keeps the
//     watermark and computes the difference itself. A resent report is then a
//     no-op instead of double-counting, and a dropped one heals on the next
//     report instead of losing traffic forever. This is the single most
//     important property of the protocol — deltas over an unreliable link
//     silently corrupt billing.
//
//  3. QUOTA IS ENFORCED ON THE NODE, NOT BY THE HUB. Asking the hub before
//     every byte is impossible; polling the hub every 30s means a user on a
//     100 Mbps line overshoots by ~375 MB. The hub instead GRANTS a bounded
//     amount of traffic and the node counts it down locally, at a resolution
//     it chooses. Overshoot then equals (local poll interval x line rate),
//     which at 1s and a rate-limited user is single-digit megabytes.
//
//  4. THE GRANT IS ALSO THE FAILURE BUDGET. If the hub becomes unreachable, a
//     node can serve at most the credit it already holds. There is no choice
//     to make between "cut everyone off on a hiccup" and "lose unbounded
//     traffic" — the grant size IS the risk, chosen deliberately per user.
//
// ============================================================================
// CREDIT CONTROL
// ============================================================================
//
// The credit mechanism is deliberately modelled on RFC 4006 (Diameter
// Credit-Control), which is the standard telecoms answer to exactly this
// problem: prepaid quota spent at distributed enforcement points that cannot
// consult the authority per packet. The names below map onto it directly so
// anyone who knows the RFC can read this without a translation table:
//
//   RFC 4006                      here
//   ------------------------------------------------------------------
//   Granted-Service-Unit          CreditGrant.granted_bytes
//   Volume-Quota-Threshold        CreditGrant.threshold_bytes
//   Validity-Time                 CreditGrant.validity_seconds
//   Final-Unit-Indication         CreditGrant.final
//   Final-Unit-Action TERMINATE   the node disconnects at exhaustion
//   CCR-Update                    CreditRequest with reason=THRESHOLD/VALIDITY
//   CCR-Termination               CreditRequest with reason=SESSION_ENDED
//   Credit-Control-Failure-...    CreditGrant.on_hub_unreachable
//
// The lifecycle, straight from the RFC's state machine:
//
//   session starts -> node asks for credit (INITIAL)
//   hub grants N bytes, threshold T, validity V
//   node counts down locally
//     consumed >= N - T ......... ask again (THRESHOLD) — early, so that a slow
//                                 answer does not interrupt a paying customer
//     V elapses ................. ask again (VALIDITY) — reconciles an idle
//                                 user and proves the link still works
//     consumed >= N and final ... disconnect NOW, no further asking
//     consumed >= N and !final .. apply on_hub_unreachable
//   session ends .............. report final usage (SESSION_ENDED)
//
// The last grant before a user's quota runs out is exact and carries final=true,
// so the only overshoot that ever reaches the customer's bill is one poll
// interval of traffic — not one grant.
//
// ============================================================================
// COMPATIBILITY
// ============================================================================
//
// Fields are only ever added, never renumbered or reused. New HubMessage
// variants are ignored by older agents, which is what lets a node run an old
// binary for weeks without breaking. protocol_version is bumped ONLY for a
// change that an old agent would misread rather than ignore.

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreditRequest_Reason int32

const (
	CreditRequest_INITIAL       CreditRequest_Reason = 0 // session just started, no credit held
	CreditRequest_THRESHOLD     CreditRequest_Reason = 1 // consumed past threshold, asking before running out
	CreditRequest_VALIDITY      CreditRequest_Reason = 2 // validity elapsed; reconcile even though credit remains
	CreditRequest_SESSION_ENDED CreditRequest_Reason = 3 // final report, no more credit wanted
	CreditRequest_EXHAUSTED     CreditRequest_Reason = 4 // ran out before an answer arrived; asking once more
)

// Enum value maps for CreditRequest_Reason.
var (
	CreditRequest_Reason_name = map[int32]string{
		0: "INITIAL",
		1: "THRESHOLD",
		2: "VALIDITY",
		3: "SESSION_ENDED",
		4: "EXHAUSTED",
	}
	CreditRequest_Reason_value = map[string]int32{
		"INITIAL":       0,
		"THRESHOLD":     1,
		"VALIDITY":      2,
		"SESSION_ENDED": 3,
		"EXHAUSTED":     4,
	}
)

func (x CreditRequest_Reason) Enum() *CreditRequest_Reason {
	p := new(CreditRequest_Reason)
	*p = x
	return p
}

func (x CreditRequest_Reason) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreditRequest_Reason) Descriptor() protoreflect.EnumDescriptor {
	return file_athena_node_v1_nodehub_proto_enumTypes[0].Descriptor()
}

func (CreditRequest_Reason) Type() protoreflect.EnumType {
	return &file_athena_node_v1_nodehub_proto_enumTypes[0]
}

func (x CreditRequest_Reason) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreditRequest_Reason.Descriptor instead.
func (CreditRequest_Reason) EnumDescriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{6, 0}
}

type CreditGrant_FailureAction int32

const (
	// Keep serving on the credit already held, then stop. The grant is the
	// budget; this is the default because cutting a paying customer off over a
	// brief control-plane hiccup is worse than the bounded loss.
	CreditGrant_CONTINUE_THEN_TERMINATE CreditGrant_FailureAction = 0
	// Stop the moment the hub is unreachable, without spending the rest.
	CreditGrant_TERMINATE_IMMEDIATELY CreditGrant_FailureAction = 1
)

// Enum value maps for CreditGrant_FailureAction.
var (
	CreditGrant_FailureAction_name = map[int32]string{
		0: "CONTINUE_THEN_TERMINATE",
		1: "TERMINATE_IMMEDIATELY",
	}
	CreditGrant_FailureAction_value = map[string]int32{
		"CONTINUE_THEN_TERMINATE": 0,
		"TERMINATE_IMMEDIATELY":   1,
	}
)

func (x CreditGrant_FailureAction) Enum() *CreditGrant_FailureAction {
	p := new(CreditGrant_FailureAction)
	*p = x
	return p
}

func (x CreditGrant_FailureAction) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (CreditGrant_FailureAction) Descriptor() protoreflect.EnumDescriptor {
	return file_athena_node_v1_nodehub_proto_enumTypes[1].Descriptor()
}

func (CreditGrant_FailureAction) Type() protoreflect.EnumType {
	return &file_athena_node_v1_nodehub_proto_enumTypes[1]
}

func (x CreditGrant_FailureAction) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use CreditGrant_FailureAction.Descriptor instead.
func (CreditGrant_FailureAction) EnumDescriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{11, 0}
}

type AgentMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentMessage_Hello
	//	*AgentMessage_Report
	//	*AgentMessage_CreditRequest
	//	*AgentMessage_SyncAck
	Payload       isAgentMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentMessage) Reset() {
	*x = AgentMessage{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentMessage) ProtoMessage() {}

func (x *AgentMessage) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentMessage.ProtoReflect.Descriptor instead.
func (*AgentMessage) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{0}
}

func (x *AgentMessage) GetPayload() isAgentMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentMessage) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentMessage) GetReport() *Report {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_Report); ok {
			return x.Report
		}
	}
	return nil
}

func (x *AgentMessage) GetCreditRequest() *CreditRequest {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_CreditRequest); ok {
			return x.CreditRequest
		}
	}
	return nil
}

func (x *AgentMessage) GetSyncAck() *SyncAck {
	if x != nil {
		if x, ok := x.Payload.(*AgentMessage_SyncAck); ok {
			return x.SyncAck
		}
	}
	return nil
}

type isAgentMessage_Payload interface {
	isAgentMessage_Payload()
}

type AgentMessage_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"` // exactly once, first
}

type AgentMessage_Report struct {
	Report *Report `protobuf:"bytes,2,opt,name=report,proto3,oneof"` // then periodically, forever
}

type AgentMessage_CreditRequest struct {
	CreditRequest *CreditRequest `protobuf:"bytes,3,opt,name=credit_request,json=creditRequest,proto3,oneof"` // whenever a session needs credit
}

type AgentMessage_SyncAck struct {
	SyncAck *SyncAck `protobuf:"bytes,4,opt,name=sync_ack,json=syncAck,proto3,oneof"` // result of applying a UserSync
}

func (*AgentMessage_Hello) isAgentMessage_Payload() {}

func (*AgentMessage_Report) isAgentMessage_Payload() {}

func (*AgentMessage_CreditRequest) isAgentMessage_Payload() {}

func (*AgentMessage_SyncAck) isAgentMessage_Payload() {}

type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Per-node shared secret. Also sent as gRPC metadata; carried here too so a
	// stream can be authenticated from its first frame regardless of transport.
	Token        string `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	AgentVersion string `protobuf:"bytes,2,opt,name=agent_version,json=agentVersion,proto3" json:"agent_version,omitempty"`
	// Bumped only on an incompatible change. The hub refuses a version it cannot
	// speak rather than silently misreading it.
	ProtocolVersion uint32 `protobuf:"varint,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	Hostname        string `protobuf:"bytes,4,opt,name=hostname,proto3" json:"hostname,omitempty"`
	Os              string `protobuf:"bytes,5,opt,name=os,proto3" json:"os,omitempty"`
	Kernel          string `protobuf:"bytes,6,opt,name=kernel,proto3" json:"kernel,omitempty"`
	// What this node can actually terminate. A node that runs only WireGuard
	// should never be sent L2TP accounts.
	HasL2Tp      bool `protobuf:"varint,7,opt,name=has_l2tp,json=hasL2tp,proto3" json:"has_l2tp,omitempty"`
	HasSstp      bool `protobuf:"varint,8,opt,name=has_sstp,json=hasSstp,proto3" json:"has_sstp,omitempty"`
	HasWireguard bool `protobuf:"varint,9,opt,name=has_wireguard,json=hasWireguard,proto3" json:"has_wireguard,omitempty"`
	// This node's OWN WireGuard server key. A customer's config must name the
	// key of the machine they actually connect to, so it cannot be a panel-wide
	// value — the master's key would produce a config that never handshakes.
	WgPublicKey string `protobuf:"bytes,10,opt,name=wg_public_key,json=wgPublicKey,proto3" json:"wg_public_key,omitempty"`
	// Where that interface listens, so the panel hands out the right port even
	// when a node was bootstrapped on a non-default one.
	WgListenPort  uint32 `protobuf:"varint,11,opt,name=wg_listen_port,json=wgListenPort,proto3" json:"wg_listen_port,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{1}
}

func (x *Hello) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *Hello) GetAgentVersion() string {
	if x != nil {
		return x.AgentVersion
	}
	return ""
}

func (x *Hello) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Hello) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *Hello) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *Hello) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *Hello) GetHasL2Tp() bool {
	if x != nil {
		return x.HasL2Tp
	}
	return false
}

func (x *Hello) GetHasSstp() bool {
	if x != nil {
		return x.HasSstp
	}
	return false
}

func (x *Hello) GetHasWireguard() bool {
	if x != nil {
		return x.HasWireguard
	}
	return false
}

func (x *Hello) GetWgPublicKey() string {
	if x != nil {
		return x.WgPublicKey
	}
	return ""
}

func (x *Hello) GetWgListenPort() uint32 {
	if x != nil {
		return x.WgListenPort
	}
	return 0
}

type Report struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	SentAtUnixMs int64                  `protobuf:"varint,1,opt,name=sent_at_unix_ms,json=sentAtUnixMs,proto3" json:"sent_at_unix_ms,omitempty"`
	Host         *Host                  `protobuf:"bytes,2,opt,name=host,proto3" json:"host,omitempty"`
	Ppp          []*PppSession          `protobuf:"bytes,3,rep,name=ppp,proto3" json:"ppp,omitempty"`
	Wg           []*WgPeer              `protobuf:"bytes,4,rep,name=wg,proto3" json:"wg,omitempty"`
	// Set when the interface scan itself failed. The hub must then treat the
	// session list as UNKNOWN rather than empty — an empty list from a failed
	// scan is indistinguishable from "everybody disconnected", and acting on
	// that difference is how sessions get finalized and billed twice.
	PppScanFailed bool `protobuf:"varint,5,opt,name=ppp_scan_failed,json=pppScanFailed,proto3" json:"ppp_scan_failed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Report) Reset() {
	*x = Report{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Report) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Report) ProtoMessage() {}

func (x *Report) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Report.ProtoReflect.Descriptor instead.
func (*Report) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{2}
}

func (x *Report) GetSentAtUnixMs() int64 {
	if x != nil {
		return x.SentAtUnixMs
	}
	return 0
}

func (x *Report) GetHost() *Host {
	if x != nil {
		return x.Host
	}
	return nil
}

func (x *Report) GetPpp() []*PppSession {
	if x != nil {
		return x.Ppp
	}
	return nil
}

func (x *Report) GetWg() []*WgPeer {
	if x != nil {
		return x.Wg
	}
	return nil
}

func (x *Report) GetPppScanFailed() bool {
	if x != nil {
		return x.PppScanFailed
	}
	return false
}

type Host struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	UptimeSeconds     uint64                 `protobuf:"varint,1,opt,name=uptime_seconds,json=uptimeSeconds,proto3" json:"uptime_seconds,omitempty"`
	Load1             float64                `protobuf:"fixed64,2,opt,name=load1,proto3" json:"load1,omitempty"`
	MemTotalBytes     uint64                 `protobuf:"varint,3,opt,name=mem_total_bytes,json=memTotalBytes,proto3" json:"mem_total_bytes,omitempty"`
	MemAvailableBytes uint64                 `protobuf:"varint,4,opt,name=mem_available_bytes,json=memAvailableBytes,proto3" json:"mem_available_bytes,omitempty"`
	// Whether the node's own VPN engines are alive. A node that reports but
	// whose engines are down is a different failure from one that is silent.
	Xl2TpdOk      bool `protobuf:"varint,5,opt,name=xl2tpd_ok,json=xl2tpdOk,proto3" json:"xl2tpd_ok,omitempty"`
	IpsecOk       bool `protobuf:"varint,6,opt,name=ipsec_ok,json=ipsecOk,proto3" json:"ipsec_ok,omitempty"`
	AccelPppOk    bool `protobuf:"varint,7,opt,name=accel_ppp_ok,json=accelPppOk,proto3" json:"accel_ppp_ok,omitempty"`
	WireguardOk   bool `protobuf:"varint,8,opt,name=wireguard_ok,json=wireguardOk,proto3" json:"wireguard_ok,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Host) Reset() {
	*x = Host{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Host) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Host) ProtoMessage() {}

func (x *Host) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Host.ProtoReflect.Descriptor instead.
func (*Host) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{3}
}

func (x *Host) GetUptimeSeconds() uint64 {
	if x != nil {
		return x.UptimeSeconds
	}
	return 0
}

func (x *Host) GetLoad1() float64 {
	if x != nil {
		return x.Load1
	}
	return 0
}

func (x *Host) GetMemTotalBytes() uint64 {
	if x != nil {
		return x.MemTotalBytes
	}
	return 0
}

func (x *Host) GetMemAvailableBytes() uint64 {
	if x != nil {
		return x.MemAvailableBytes
	}
	return 0
}

func (x *Host) GetXl2TpdOk() bool {
	if x != nil {
		return x.Xl2TpdOk
	}
	return false
}

func (x *Host) GetIpsecOk() bool {
	if x != nil {
		return x.IpsecOk
	}
	return false
}

func (x *Host) GetAccelPppOk() bool {
	if x != nil {
		return x.AccelPppOk
	}
	return false
}

func (x *Host) GetWireguardOk() bool {
	if x != nil {
		return x.WireguardOk
	}
	return false
}

// One live ppp interface. ABSOLUTE kernel counters since the interface came up.
type PppSession struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Ifname  string                 `protobuf:"bytes,1,opt,name=ifname,proto3" json:"ifname,omitempty"`
	RxBytes uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"` // from the client  (the user's upload)
	TxBytes uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"` // toward the client (the user's download)
	// Empty when the agent cannot map the interface to an account. The hub must
	// treat that as "unknown", never as "no user" -- silently dropping unmapped
	// traffic is how usage goes missing.
	Username      string `protobuf:"bytes,4,opt,name=username,proto3" json:"username,omitempty"`
	PeerIp        string `protobuf:"bytes,5,opt,name=peer_ip,json=peerIp,proto3" json:"peer_ip,omitempty"`
	Pid           int32  `protobuf:"varint,6,opt,name=pid,proto3" json:"pid,omitempty"` // meaningful ONLY on the node that reported it
	StartedAtUnix int64  `protobuf:"varint,7,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PppSession) Reset() {
	*x = PppSession{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PppSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PppSession) ProtoMessage() {}

func (x *PppSession) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PppSession.ProtoReflect.Descriptor instead.
func (*PppSession) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{4}
}

func (x *PppSession) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

func (x *PppSession) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *PppSession) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *PppSession) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *PppSession) GetPeerIp() string {
	if x != nil {
		return x.PeerIp
	}
	return ""
}

func (x *PppSession) GetPid() int32 {
	if x != nil {
		return x.Pid
	}
	return 0
}

func (x *PppSession) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

// One WireGuard peer. ABSOLUTE counters since the peer was added.
type WgPeer struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PublicKey         string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	RxBytes           uint64                 `protobuf:"varint,2,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	TxBytes           uint64                 `protobuf:"varint,3,opt,name=tx_bytes,json=txBytes,proto3" json:"tx_bytes,omitempty"`
	LastHandshakeUnix int64                  `protobuf:"varint,4,opt,name=last_handshake_unix,json=lastHandshakeUnix,proto3" json:"last_handshake_unix,omitempty"` // 0 = never
	Address           string                 `protobuf:"bytes,5,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *WgPeer) Reset() {
	*x = WgPeer{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WgPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WgPeer) ProtoMessage() {}

func (x *WgPeer) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WgPeer.ProtoReflect.Descriptor instead.
func (*WgPeer) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{5}
}

func (x *WgPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *WgPeer) GetRxBytes() uint64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *WgPeer) GetTxBytes() uint64 {
	if x != nil {
		return x.TxBytes
	}
	return 0
}

func (x *WgPeer) GetLastHandshakeUnix() int64 {
	if x != nil {
		return x.LastHandshakeUnix
	}
	return 0
}

func (x *WgPeer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

// Asks for credit to keep serving a user. Always carries the usage consumed
// so far, so a request doubles as a usage report and the two can never
// disagree about what has been spent.
type CreditRequest struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Username string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Reason   CreditRequest_Reason   `protobuf:"varint,2,opt,name=reason,proto3,enum=athena.node.v1.CreditRequest_Reason" json:"reason,omitempty"`
	// Consumed under the CURRENT grant, in bytes. Reset by the agent each time a
	// new grant is applied, so it is always relative to grant_id — which makes a
	// duplicate delivery harmless.
	ConsumedBytes uint64 `protobuf:"varint,3,opt,name=consumed_bytes,json=consumedBytes,proto3" json:"consumed_bytes,omitempty"`
	// Which grant this consumption belongs to. A request quoting a grant the hub
	// has already superseded is stale and its consumption is dropped rather than
	// applied twice.
	GrantId uint64 `protobuf:"varint,4,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	// Absolute counters of the session behind this request, so the hub can
	// cross-check the credit ledger against the traffic ledger and notice drift
	// instead of trusting one of them blindly.
	SessionRxBytes uint64 `protobuf:"varint,5,opt,name=session_rx_bytes,json=sessionRxBytes,proto3" json:"session_rx_bytes,omitempty"`
	SessionTxBytes uint64 `protobuf:"varint,6,opt,name=session_tx_bytes,json=sessionTxBytes,proto3" json:"session_tx_bytes,omitempty"`
	Ifname         string `protobuf:"bytes,7,opt,name=ifname,proto3" json:"ifname,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreditRequest) Reset() {
	*x = CreditRequest{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditRequest) ProtoMessage() {}

func (x *CreditRequest) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditRequest.ProtoReflect.Descriptor instead.
func (*CreditRequest) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{6}
}

func (x *CreditRequest) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreditRequest) GetReason() CreditRequest_Reason {
	if x != nil {
		return x.Reason
	}
	return CreditRequest_INITIAL
}

func (x *CreditRequest) GetConsumedBytes() uint64 {
	if x != nil {
		return x.ConsumedBytes
	}
	return 0
}

func (x *CreditRequest) GetGrantId() uint64 {
	if x != nil {
		return x.GrantId
	}
	return 0
}

func (x *CreditRequest) GetSessionRxBytes() uint64 {
	if x != nil {
		return x.SessionRxBytes
	}
	return 0
}

func (x *CreditRequest) GetSessionTxBytes() uint64 {
	if x != nil {
		return x.SessionTxBytes
	}
	return 0
}

func (x *CreditRequest) GetIfname() string {
	if x != nil {
		return x.Ifname
	}
	return ""
}

type SyncAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SyncId        uint64                 `protobuf:"varint,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	Ok            bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail        string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	UsersApplied  uint32                 `protobuf:"varint,4,opt,name=users_applied,json=usersApplied,proto3" json:"users_applied,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SyncAck) Reset() {
	*x = SyncAck{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SyncAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SyncAck) ProtoMessage() {}

func (x *SyncAck) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SyncAck.ProtoReflect.Descriptor instead.
func (*SyncAck) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{7}
}

func (x *SyncAck) GetSyncId() uint64 {
	if x != nil {
		return x.SyncId
	}
	return 0
}

func (x *SyncAck) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *SyncAck) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

func (x *SyncAck) GetUsersApplied() uint32 {
	if x != nil {
		return x.UsersApplied
	}
	return 0
}

type HubMessage struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*HubMessage_Welcome
	//	*HubMessage_Ack
	//	*HubMessage_CreditGrant
	//	*HubMessage_UserSync
	//	*HubMessage_Disconnect
	Payload       isHubMessage_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HubMessage) Reset() {
	*x = HubMessage{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HubMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HubMessage) ProtoMessage() {}

func (x *HubMessage) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HubMessage.ProtoReflect.Descriptor instead.
func (*HubMessage) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{8}
}

func (x *HubMessage) GetPayload() isHubMessage_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *HubMessage) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *HubMessage) GetAck() *Ack {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_Ack); ok {
			return x.Ack
		}
	}
	return nil
}

func (x *HubMessage) GetCreditGrant() *CreditGrant {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_CreditGrant); ok {
			return x.CreditGrant
		}
	}
	return nil
}

func (x *HubMessage) GetUserSync() *UserSync {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_UserSync); ok {
			return x.UserSync
		}
	}
	return nil
}

func (x *HubMessage) GetDisconnect() *Disconnect {
	if x != nil {
		if x, ok := x.Payload.(*HubMessage_Disconnect); ok {
			return x.Disconnect
		}
	}
	return nil
}

type isHubMessage_Payload interface {
	isHubMessage_Payload()
}

type HubMessage_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type HubMessage_Ack struct {
	Ack *Ack `protobuf:"bytes,2,opt,name=ack,proto3,oneof"`
}

type HubMessage_CreditGrant struct {
	CreditGrant *CreditGrant `protobuf:"bytes,3,opt,name=credit_grant,json=creditGrant,proto3,oneof"`
}

type HubMessage_UserSync struct {
	UserSync *UserSync `protobuf:"bytes,4,opt,name=user_sync,json=userSync,proto3,oneof"`
}

type HubMessage_Disconnect struct {
	Disconnect *Disconnect `protobuf:"bytes,5,opt,name=disconnect,proto3,oneof"`
}

func (*HubMessage_Welcome) isHubMessage_Payload() {}

func (*HubMessage_Ack) isHubMessage_Payload() {}

func (*HubMessage_CreditGrant) isHubMessage_Payload() {}

func (*HubMessage_UserSync) isHubMessage_Payload() {}

func (*HubMessage_Disconnect) isHubMessage_Payload() {}

type Welcome struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	NodeId                int32                  `protobuf:"varint,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	NodeName              string                 `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ReportIntervalSeconds uint32                 `protobuf:"varint,3,opt,name=report_interval_seconds,json=reportIntervalSeconds,proto3" json:"report_interval_seconds,omitempty"`
	ProtocolVersion       uint32                 `protobuf:"varint,4,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// How often the node should sample its own interfaces for credit purposes.
	// This is the knob that sets accuracy: overshoot is bounded by this interval
	// times the user's line rate. Separate from report_interval_seconds, which
	// only governs telemetry sent upstream.
	CreditPollMs  uint32 `protobuf:"varint,5,opt,name=credit_poll_ms,json=creditPollMs,proto3" json:"credit_poll_ms,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{9}
}

func (x *Welcome) GetNodeId() int32 {
	if x != nil {
		return x.NodeId
	}
	return 0
}

func (x *Welcome) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Welcome) GetReportIntervalSeconds() uint32 {
	if x != nil {
		return x.ReportIntervalSeconds
	}
	return 0
}

func (x *Welcome) GetProtocolVersion() uint32 {
	if x != nil {
		return x.ProtocolVersion
	}
	return 0
}

func (x *Welcome) GetCreditPollMs() uint32 {
	if x != nil {
		return x.CreditPollMs
	}
	return 0
}

type Ack struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	ReceivedAtUnixMs int64                  `protobuf:"varint,1,opt,name=received_at_unix_ms,json=receivedAtUnixMs,proto3" json:"received_at_unix_ms,omitempty"`
	Ok               bool                   `protobuf:"varint,2,opt,name=ok,proto3" json:"ok,omitempty"`
	Detail           string                 `protobuf:"bytes,3,opt,name=detail,proto3" json:"detail,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *Ack) Reset() {
	*x = Ack{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Ack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Ack) ProtoMessage() {}

func (x *Ack) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Ack.ProtoReflect.Descriptor instead.
func (*Ack) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{10}
}

func (x *Ack) GetReceivedAtUnixMs() int64 {
	if x != nil {
		return x.ReceivedAtUnixMs
	}
	return 0
}

func (x *Ack) GetOk() bool {
	if x != nil {
		return x.Ok
	}
	return false
}

func (x *Ack) GetDetail() string {
	if x != nil {
		return x.Detail
	}
	return ""
}

// Authority to keep serving a user for a bounded amount of traffic.
type CreditGrant struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Username string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	GrantId  uint64                 `protobuf:"varint,2,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	// Bytes the node may serve before it must ask again. Counted from zero at
	// the moment the grant is applied.
	GrantedBytes uint64 `protobuf:"varint,3,opt,name=granted_bytes,json=grantedBytes,proto3" json:"granted_bytes,omitempty"`
	// Ask for more once this much of the grant remains. Chosen so the round trip
	// completes before the customer would have been interrupted.
	ThresholdBytes uint64 `protobuf:"varint,4,opt,name=threshold_bytes,json=thresholdBytes,proto3" json:"threshold_bytes,omitempty"`
	// Re-ask after this long even if the traffic threshold is never reached, so
	// an idle session still reconciles and a dead link is noticed.
	ValiditySeconds uint32 `protobuf:"varint,5,opt,name=validity_seconds,json=validitySeconds,proto3" json:"validity_seconds,omitempty"`
	// These are the user's LAST bytes. The node terminates at exhaustion and does
	// not ask again. Only ever set when the remaining quota fits in one grant, so
	// the overshoot a customer can see is one poll interval, not one grant.
	Final            bool                      `protobuf:"varint,6,opt,name=final,proto3" json:"final,omitempty"`
	OnHubUnreachable CreditGrant_FailureAction `protobuf:"varint,7,opt,name=on_hub_unreachable,json=onHubUnreachable,proto3,enum=athena.node.v1.CreditGrant_FailureAction" json:"on_hub_unreachable,omitempty"`
	// Zero means "no credit": the hub is refusing service for this user (expired,
	// disabled, over quota, wrong node). The node disconnects them at once.
	Refused       bool   `protobuf:"varint,8,opt,name=refused,proto3" json:"refused,omitempty"`
	RefuseReason  string `protobuf:"bytes,9,opt,name=refuse_reason,json=refuseReason,proto3" json:"refuse_reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreditGrant) Reset() {
	*x = CreditGrant{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreditGrant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreditGrant) ProtoMessage() {}

func (x *CreditGrant) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreditGrant.ProtoReflect.Descriptor instead.
func (*CreditGrant) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{11}
}

func (x *CreditGrant) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *CreditGrant) GetGrantId() uint64 {
	if x != nil {
		return x.GrantId
	}
	return 0
}

func (x *CreditGrant) GetGrantedBytes() uint64 {
	if x != nil {
		return x.GrantedBytes
	}
	return 0
}

func (x *CreditGrant) GetThresholdBytes() uint64 {
	if x != nil {
		return x.ThresholdBytes
	}
	return 0
}

func (x *CreditGrant) GetValiditySeconds() uint32 {
	if x != nil {
		return x.ValiditySeconds
	}
	return 0
}

func (x *CreditGrant) GetFinal() bool {
	if x != nil {
		return x.Final
	}
	return false
}

func (x *CreditGrant) GetOnHubUnreachable() CreditGrant_FailureAction {
	if x != nil {
		return x.OnHubUnreachable
	}
	return CreditGrant_CONTINUE_THEN_TERMINATE
}

func (x *CreditGrant) GetRefused() bool {
	if x != nil {
		return x.Refused
	}
	return false
}

func (x *CreditGrant) GetRefuseReason() string {
	if x != nil {
		return x.RefuseReason
	}
	return ""
}

// The set of accounts this node should accept. Sent whole rather than as a
// diff: a node that missed an update would otherwise diverge silently, and the
// list is small enough that idempotent replacement is cheaper than being clever.
type UserSync struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	SyncId uint64                 `protobuf:"varint,1,opt,name=sync_id,json=syncId,proto3" json:"sync_id,omitempty"`
	Users  []*UserSync_Entry      `protobuf:"bytes,2,rep,name=users,proto3" json:"users,omitempty"`
	// True when this is the complete list. A partial sync is not currently sent;
	// the field exists so adding one later cannot be mistaken for a full one.
	Full          bool `protobuf:"varint,3,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSync) Reset() {
	*x = UserSync{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSync) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSync) ProtoMessage() {}

func (x *UserSync) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSync.ProtoReflect.Descriptor instead.
func (*UserSync) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{12}
}

func (x *UserSync) GetSyncId() uint64 {
	if x != nil {
		return x.SyncId
	}
	return 0
}

func (x *UserSync) GetUsers() []*UserSync_Entry {
	if x != nil {
		return x.Users
	}
	return nil
}

func (x *UserSync) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

// Drop a user's sessions now.
type Disconnect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Username      string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Reason        string                 `protobuf:"bytes,2,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Disconnect) Reset() {
	*x = Disconnect{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Disconnect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Disconnect) ProtoMessage() {}

func (x *Disconnect) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Disconnect.ProtoReflect.Descriptor instead.
func (*Disconnect) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{13}
}

func (x *Disconnect) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *Disconnect) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type UserSync_Entry struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	Username     string                 `protobuf:"bytes,1,opt,name=username,proto3" json:"username,omitempty"`
	Password     string                 `protobuf:"bytes,2,opt,name=password,proto3" json:"password,omitempty"`
	Enabled      bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	RateDownKbps uint32                 `protobuf:"varint,4,opt,name=rate_down_kbps,json=rateDownKbps,proto3" json:"rate_down_kbps,omitempty"`
	RateUpKbps   uint32                 `protobuf:"varint,5,opt,name=rate_up_kbps,json=rateUpKbps,proto3" json:"rate_up_kbps,omitempty"`
	// "ipsec" | "raw" — which L2TP endpoint this account may use.
	L2TpMode string `protobuf:"bytes,6,opt,name=l2tp_mode,json=l2tpMode,proto3" json:"l2tp_mode,omitempty"`
	// "direct" | "warp"
	Outbound string `protobuf:"bytes,7,opt,name=outbound,proto3" json:"outbound,omitempty"`
	// Every WireGuard peer belonging to this account. Sent with the account
	// rather than as a separate list so a node can never end up serving a peer
	// whose owner it does not know — that is what makes the peer's traffic
	// billable instead of anonymous.
	WgPeers       []*UserSync_WgPeer `protobuf:"bytes,8,rep,name=wg_peers,json=wgPeers,proto3" json:"wg_peers,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSync_Entry) Reset() {
	*x = UserSync_Entry{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSync_Entry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSync_Entry) ProtoMessage() {}

func (x *UserSync_Entry) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSync_Entry.ProtoReflect.Descriptor instead.
func (*UserSync_Entry) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{12, 0}
}

func (x *UserSync_Entry) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

func (x *UserSync_Entry) GetPassword() string {
	if x != nil {
		return x.Password
	}
	return ""
}

func (x *UserSync_Entry) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *UserSync_Entry) GetRateDownKbps() uint32 {
	if x != nil {
		return x.RateDownKbps
	}
	return 0
}

func (x *UserSync_Entry) GetRateUpKbps() uint32 {
	if x != nil {
		return x.RateUpKbps
	}
	return 0
}

func (x *UserSync_Entry) GetL2TpMode() string {
	if x != nil {
		return x.L2TpMode
	}
	return ""
}

func (x *UserSync_Entry) GetOutbound() string {
	if x != nil {
		return x.Outbound
	}
	return ""
}

func (x *UserSync_Entry) GetWgPeers() []*UserSync_WgPeer {
	if x != nil {
		return x.WgPeers
	}
	return nil
}

type UserSync_WgPeer struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	PublicKey    string                 `protobuf:"bytes,1,opt,name=public_key,json=publicKey,proto3" json:"public_key,omitempty"`
	PresharedKey string                 `protobuf:"bytes,2,opt,name=preshared_key,json=presharedKey,proto3" json:"preshared_key,omitempty"`
	// The single /32 this peer is allowed to use, which is also how the node
	// NATs it. One address per peer: WireGuard has no session, so the address
	// IS the identity for anything downstream (WARP routing, firewalling).
	Address       string `protobuf:"bytes,3,opt,name=address,proto3" json:"address,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UserSync_WgPeer) Reset() {
	*x = UserSync_WgPeer{}
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UserSync_WgPeer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UserSync_WgPeer) ProtoMessage() {}

func (x *UserSync_WgPeer) ProtoReflect() protoreflect.Message {
	mi := &file_athena_node_v1_nodehub_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UserSync_WgPeer.ProtoReflect.Descriptor instead.
func (*UserSync_WgPeer) Descriptor() ([]byte, []int) {
	return file_athena_node_v1_nodehub_proto_rawDescGZIP(), []int{12, 1}
}

func (x *UserSync_WgPeer) GetPublicKey() string {
	if x != nil {
		return x.PublicKey
	}
	return ""
}

func (x *UserSync_WgPeer) GetPresharedKey() string {
	if x != nil {
		return x.PresharedKey
	}
	return ""
}

func (x *UserSync_WgPeer) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

var File_athena_node_v1_nodehub_proto protoreflect.FileDescriptor

var file_athena_node_v1_nodehub_proto_rawDesc = []byte{
	0x0a, 0x1c, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x2f, 0x76, 0x31,
	0x2f, 0x6e, 0x6f, 0x64, 0x65, 0x68, 0x75, 0x62, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0e,
	0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x22, 0xf8,
	0x01, 0x0a, 0x0c, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12,
	0x2d, 0x0a, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x15,
	0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x48, 0x00, 0x52, 0x05, 0x68, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x30,
	0x0a, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x16,
	0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x48, 0x00, 0x52, 0x06, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74,
	0x12, 0x46, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x72, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e,
	0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74,
	0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x48, 0x00, 0x52, 0x0d, 0x63, 0x72, 0x65, 0x64, 0x69,
	0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x34, 0x0a, 0x08, 0x73, 0x79, 0x6e, 0x63,
	0x5f, 0x61, 0x63, 0x6b, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17, 0x2e, 0x61, 0x74, 0x68,
	0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x53, 0x79, 0x6e, 0x63,
	0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x07, 0x73, 0x79, 0x6e, 0x63, 0x41, 0x63, 0x6b, 0x42, 0x09,
	0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0xd6, 0x02, 0x0a, 0x05, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x12, 0x14, 0x0a, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x05, 0x74, 0x6f, 0x6b, 0x65, 0x6e, 0x12, 0x23, 0x0a, 0x0d, 0x61, 0x67, 0x65,
	0x6e, 0x74, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0c, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x29,
	0x0a, 0x10, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63,
	0x6f, 0x6c, 0x56, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x1a, 0x0a, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x68, 0x6f, 0x73,
	0x74, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x02, 0x6f, 0x73, 0x12, 0x16, 0x0a, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x18,
	0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x6b, 0x65, 0x72, 0x6e, 0x65, 0x6c, 0x12, 0x19, 0x0a,
	0x08, 0x68, 0x61, 0x73, 0x5f, 0x6c, 0x32, 0x74, 0x70, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52,
	0x07, 0x68, 0x61, 0x73, 0x4c, 0x32, 0x74, 0x70, 0x12, 0x19, 0x0a, 0x08, 0x68, 0x61, 0x73, 0x5f,
	0x73, 0x73, 0x74, 0x70, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x68, 0x61, 0x73, 0x53,
	0x73, 0x74, 0x70, 0x12, 0x23, 0x0a, 0x0d, 0x68, 0x61, 0x73, 0x5f, 0x77, 0x69, 0x72, 0x65, 0x67,
	0x75, 0x61, 0x72, 0x64, 0x18, 0x09, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0c, 0x68, 0x61, 0x73, 0x57,
	0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72, 0x64, 0x12, 0x22, 0x0a, 0x0d, 0x77, 0x67, 0x5f, 0x70,
	0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x0a, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x0b, 0x77, 0x67, 0x50, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x24, 0x0a, 0x0e,
	0x77, 0x67, 0x5f, 0x6c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x5f, 0x70, 0x6f, 0x72, 0x74, 0x18, 0x0b,
	0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x77, 0x67, 0x4c, 0x69, 0x73, 0x74, 0x65, 0x6e, 0x50, 0x6f,
	0x72, 0x74, 0x22, 0xd7, 0x01, 0x0a, 0x06, 0x52, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x12, 0x25, 0x0a,
	0x0f, 0x73, 0x65, 0x6e, 0x74, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0c, 0x73, 0x65, 0x6e, 0x74, 0x41, 0x74, 0x55, 0x6e,
	0x69, 0x78, 0x4d, 0x73, 0x12, 0x28, 0x0a, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x0b, 0x32, 0x14, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65,
	0x2e, 0x76, 0x31, 0x2e, 0x48, 0x6f, 0x73, 0x74, 0x52, 0x04, 0x68, 0x6f, 0x73, 0x74, 0x12, 0x2c,
	0x0a, 0x03, 0x70, 0x70, 0x70, 0x18, 0x03, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x74,
	0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x50, 0x70, 0x70,
	0x53, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x03, 0x70, 0x70, 0x70, 0x12, 0x26, 0x0a, 0x02,
	0x77, 0x67, 0x18, 0x04, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x16, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e,
	0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x57, 0x67, 0x50, 0x65, 0x65, 0x72,
	0x52, 0x02, 0x77, 0x67, 0x12, 0x26, 0x0a, 0x0f, 0x70, 0x70, 0x70, 0x5f, 0x73, 0x63, 0x61, 0x6e,
	0x5f, 0x66, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0d, 0x70,
	0x70, 0x70, 0x53, 0x63, 0x61, 0x6e, 0x46, 0x61, 0x69, 0x6c, 0x65, 0x64, 0x22, 0x98, 0x02, 0x0a,
	0x04, 0x48, 0x6f, 0x73, 0x74, 0x12, 0x25, 0x0a, 0x0e, 0x75, 0x70, 0x74, 0x69, 0x6d, 0x65, 0x5f,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x75,
	0x70, 0x74, 0x69, 0x6d, 0x65, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05,
	0x6c, 0x6f, 0x61, 0x64, 0x31, 0x18, 0x02, 0x20, 0x01, 0x28, 0x01, 0x52, 0x05, 0x6c, 0x6f, 0x61,
	0x64, 0x31, 0x12, 0x26, 0x0a, 0x0f, 0x6d, 0x65, 0x6d, 0x5f, 0x74, 0x6f, 0x74, 0x61, 0x6c, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0d, 0x6d, 0x65, 0x6d,
	0x54, 0x6f, 0x74, 0x61, 0x6c, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x6d, 0x65,
	0x6d, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65,
	0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x11, 0x6d, 0x65, 0x6d, 0x41, 0x76, 0x61, 0x69,
	0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x78, 0x6c,
	0x32, 0x74, 0x70, 0x64, 0x5f, 0x6f, 0x6b, 0x18, 0x05, 0x20, 0x01, 0x28, 0x08, 0x52, 0x08, 0x78,
	0x6c, 0x32, 0x74, 0x70, 0x64, 0x4f, 0x6b, 0x12, 0x19, 0x0a, 0x08, 0x69, 0x70, 0x73, 0x65, 0x63,
	0x5f, 0x6f, 0x6b, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x69, 0x70, 0x73, 0x65, 0x63,
	0x4f, 0x6b, 0x12, 0x20, 0x0a, 0x0c, 0x61, 0x63, 0x63, 0x65, 0x6c, 0x5f, 0x70, 0x70, 0x70, 0x5f,
	0x6f, 0x6b, 0x18, 0x07, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0a, 0x61, 0x63, 0x63, 0x65, 0x6c, 0x50,
	0x70, 0x70, 0x4f, 0x6b, 0x12, 0x21, 0x0a, 0x0c, 0x77, 0x69, 0x72, 0x65, 0x67, 0x75, 0x61, 0x72,
	0x64, 0x5f, 0x6f, 0x6b, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x0b, 0x77, 0x69, 0x72, 0x65,
	0x67, 0x75, 0x61, 0x72, 0x64, 0x4f, 0x6b, 0x22, 0xc9, 0x01, 0x0a, 0x0a, 0x50, 0x70, 0x70, 0x53,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x12, 0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19,
	0x0a, 0x08, 0x72, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04,
	0x52, 0x07, 0x72, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x78, 0x5f,
	0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x78, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x04, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x17, 0x0a, 0x07, 0x70, 0x65, 0x65, 0x72, 0x5f, 0x69, 0x70, 0x18, 0x05, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x70, 0x65, 0x65, 0x72, 0x49, 0x70, 0x12, 0x10, 0x0a, 0x03, 0x70, 0x69, 0x64,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x05, 0x52, 0x03, 0x70, 0x69, 0x64, 0x12, 0x26, 0x0a, 0x0f, 0x73,
	0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x5f, 0x61, 0x74, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x07,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x73, 0x74, 0x61, 0x72, 0x74, 0x65, 0x64, 0x41, 0x74, 0x55,
	0x6e, 0x69, 0x78, 0x22, 0xa7, 0x01, 0x0a, 0x06, 0x57, 0x67, 0x50, 0x65, 0x65, 0x72, 0x12, 0x1d,
	0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65, 0x79, 0x12, 0x19, 0x0a,
	0x08, 0x72, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x07, 0x72, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x19, 0x0a, 0x08, 0x74, 0x78, 0x5f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x74, 0x78, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x2e, 0x0a, 0x13, 0x6c, 0x61, 0x73, 0x74, 0x5f, 0x68, 0x61, 0x6e, 0x64,
	0x73, 0x68, 0x61, 0x6b, 0x65, 0x5f, 0x75, 0x6e, 0x69, 0x78, 0x18, 0x04, 0x20, 0x01, 0x28, 0x03,
	0x52, 0x11, 0x6c, 0x61, 0x73, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x73, 0x68, 0x61, 0x6b, 0x65, 0x55,
	0x6e, 0x69, 0x78, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x18, 0x05,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73, 0x22, 0xed, 0x02,
	0x0a, 0x0d, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12,
	0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x3c, 0x0a, 0x06, 0x72,
	0x65, 0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x24, 0x2e, 0x61, 0x74,
	0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x2e, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e,
	0x73, 0x75, 0x6d, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x04, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x73, 0x75, 0x6d, 0x65, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73,
	0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64, 0x18, 0x04, 0x20, 0x01,
	0x28, 0x04, 0x52, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12, 0x28, 0x0a, 0x10, 0x73,
	0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x5f, 0x72, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18,
	0x05, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x52, 0x78,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x28, 0x0a, 0x10, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e,
	0x5f, 0x74, 0x78, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x06, 0x20, 0x01, 0x28, 0x04, 0x52,
	0x0e, 0x73, 0x65, 0x73, 0x73, 0x69, 0x6f, 0x6e, 0x54, 0x78, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12,
	0x16, 0x0a, 0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x06, 0x69, 0x66, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x54, 0x0a, 0x06, 0x52, 0x65, 0x61, 0x73, 0x6f,
	0x6e, 0x12, 0x0b, 0x0a, 0x07, 0x49, 0x4e, 0x49, 0x54, 0x49, 0x41, 0x4c, 0x10, 0x00, 0x12, 0x0d,
	0x0a, 0x09, 0x54, 0x48, 0x52, 0x45, 0x53, 0x48, 0x4f, 0x4c, 0x44, 0x10, 0x01, 0x12, 0x0c, 0x0a,
	0x08, 0x56, 0x41, 0x4c, 0x49, 0x44, 0x49, 0x54, 0x59, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x53,
	0x45, 0x53, 0x53, 0x49, 0x4f, 0x4e, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x03, 0x12, 0x0d,
	0x0a, 0x09, 0x45, 0x58, 0x48, 0x41, 0x55, 0x53, 0x54, 0x45, 0x44, 0x10, 0x04, 0x22, 0x6f, 0x0a,
	0x07, 0x53, 0x79, 0x6e, 0x63, 0x41, 0x63, 0x6b, 0x12, 0x17, 0x0a, 0x07, 0x73, 0x79, 0x6e, 0x63,
	0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73, 0x79, 0x6e, 0x63, 0x49,
	0x64, 0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f,
	0x6b, 0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x12, 0x23, 0x0a, 0x0d, 0x75, 0x73, 0x65,
	0x72, 0x73, 0x5f, 0x61, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0d,
	0x52, 0x0c, 0x75, 0x73, 0x65, 0x72, 0x73, 0x41, 0x70, 0x70, 0x6c, 0x69, 0x65, 0x64, 0x22, 0xae,
	0x02, 0x0a, 0x0a, 0x48, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x12, 0x33, 0x0a,
	0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x17,
	0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x48, 0x00, 0x52, 0x07, 0x77, 0x65, 0x6c, 0x63, 0x6f,
	0x6d, 0x65, 0x12, 0x27, 0x0a, 0x03, 0x61, 0x63, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x0b, 0x32,
	0x13, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31,
	0x2e, 0x41, 0x63, 0x6b, 0x48, 0x00, 0x52, 0x03, 0x61, 0x63, 0x6b, 0x12, 0x40, 0x0a, 0x0c, 0x63,
	0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x18, 0x03, 0x20, 0x01, 0x28,
	0x0b, 0x32, 0x1b, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e,
	0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x64, 0x69, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x48, 0x00,
	0x52, 0x0b, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x37, 0x0a,
	0x09, 0x75, 0x73, 0x65, 0x72, 0x5f, 0x73, 0x79, 0x6e, 0x63, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b,
	0x32, 0x18, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76,
	0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x48, 0x00, 0x52, 0x08, 0x75, 0x73,
	0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x3c, 0x0a, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x1a, 0x2e, 0x61, 0x74, 0x68,
	0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x44, 0x69, 0x73, 0x63,
	0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x48, 0x00, 0x52, 0x0a, 0x64, 0x69, 0x73, 0x63, 0x6f, 0x6e,
	0x6e, 0x65, 0x63, 0x74, 0x42, 0x09, 0x0a, 0x07, 0x70, 0x61, 0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22,
	0xc8, 0x01, 0x0a, 0x07, 0x57, 0x65, 0x6c, 0x63, 0x6f, 0x6d, 0x65, 0x12, 0x17, 0x0a, 0x07, 0x6e,
	0x6f, 0x64, 0x65, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x05, 0x52, 0x06, 0x6e, 0x6f,
	0x64, 0x65, 0x49, 0x64, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d,
	0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d,
	0x65, 0x12, 0x36, 0x0a, 0x17, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x5f, 0x69, 0x6e, 0x74, 0x65,
	0x72, 0x76, 0x61, 0x6c, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x0d, 0x52, 0x15, 0x72, 0x65, 0x70, 0x6f, 0x72, 0x74, 0x49, 0x6e, 0x74, 0x65, 0x72, 0x76,
	0x61, 0x6c, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x29, 0x0a, 0x10, 0x70, 0x72, 0x6f,
	0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x5f, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f, 0x6e, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0f, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x63, 0x6f, 0x6c, 0x56, 0x65, 0x72,
	0x73, 0x69, 0x6f, 0x6e, 0x12, 0x24, 0x0a, 0x0e, 0x63, 0x72, 0x65, 0x64, 0x69, 0x74, 0x5f, 0x70,
	0x6f, 0x6c, 0x6c, 0x5f, 0x6d, 0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0c, 0x63, 0x72,
	0x65, 0x64, 0x69, 0x74, 0x50, 0x6f, 0x6c, 0x6c, 0x4d, 0x73, 0x22, 0x5c, 0x0a, 0x03, 0x41, 0x63,
	0x6b, 0x12, 0x2d, 0x0a, 0x13, 0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x5f, 0x61, 0x74,
	0x5f, 0x75, 0x6e, 0x69, 0x78, 0x5f, 0x6d, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x10,
	0x72, 0x65, 0x63, 0x65, 0x69, 0x76, 0x65, 0x64, 0x41, 0x74, 0x55, 0x6e, 0x69, 0x78, 0x4d, 0x73,
	0x12, 0x0e, 0x0a, 0x02, 0x6f, 0x6b, 0x18, 0x02, 0x20, 0x01, 0x28, 0x08, 0x52, 0x02, 0x6f, 0x6b,
	0x12, 0x16, 0x0a, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x06, 0x64, 0x65, 0x74, 0x61, 0x69, 0x6c, 0x22, 0xb4, 0x03, 0x0a, 0x0b, 0x43, 0x72, 0x65,
	0x64, 0x69, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65, 0x72,
	0x6e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x5f, 0x69, 0x64,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x04, 0x52, 0x07, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x49, 0x64, 0x12,
	0x23, 0x0a, 0x0d, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0c, 0x67, 0x72, 0x61, 0x6e, 0x74, 0x65, 0x64, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x12, 0x27, 0x0a, 0x0f, 0x74, 0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c,
	0x64, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x04, 0x20, 0x01, 0x28, 0x04, 0x52, 0x0e, 0x74,
	0x68, 0x72, 0x65, 0x73, 0x68, 0x6f, 0x6c, 0x64, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x29, 0x0a,
	0x10, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74, 0x79, 0x5f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0f, 0x76, 0x61, 0x6c, 0x69, 0x64, 0x69, 0x74,
	0x79, 0x53, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x14, 0x0a, 0x05, 0x66, 0x69, 0x6e, 0x61,
	0x6c, 0x18, 0x06, 0x20, 0x01, 0x28, 0x08, 0x52, 0x05, 0x66, 0x69, 0x6e, 0x61, 0x6c, 0x12, 0x57,
	0x0a, 0x12, 0x6f, 0x6e, 0x5f, 0x68, 0x75, 0x62, 0x5f, 0x75, 0x6e, 0x72, 0x65, 0x61, 0x63, 0x68,
	0x61, 0x62, 0x6c, 0x65, 0x18, 0x07, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x29, 0x2e, 0x61, 0x74, 0x68,
	0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x43, 0x72, 0x65, 0x64,
	0x69, 0x74, 0x47, 0x72, 0x61, 0x6e, 0x74, 0x2e, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72, 0x65, 0x41,
	0x63, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x10, 0x6f, 0x6e, 0x48, 0x75, 0x62, 0x55, 0x6e, 0x72, 0x65,
	0x61, 0x63, 0x68, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x72, 0x65, 0x66, 0x75, 0x73,
	0x65, 0x64, 0x18, 0x08, 0x20, 0x01, 0x28, 0x08, 0x52, 0x07, 0x72, 0x65, 0x66, 0x75, 0x73, 0x65,
	0x64, 0x12, 0x23, 0x0a, 0x0d, 0x72, 0x65, 0x66, 0x75, 0x73, 0x65, 0x5f, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x18, 0x09, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x72, 0x65, 0x66, 0x75, 0x73, 0x65,
	0x52, 0x65, 0x61, 0x73, 0x6f, 0x6e, 0x22, 0x47, 0x0a, 0x0d, 0x46, 0x61, 0x69, 0x6c, 0x75, 0x72,
	0x65, 0x41, 0x63, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x1b, 0x0a, 0x17, 0x43, 0x4f, 0x4e, 0x54, 0x49,
	0x4e, 0x55, 0x45, 0x5f, 0x54, 0x48, 0x45, 0x4e, 0x5f, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41,
	0x54, 0x45, 0x10, 0x00, 0x12, 0x19, 0x0a, 0x15, 0x54, 0x45, 0x52, 0x4d, 0x49, 0x4e, 0x41, 0x54,
	0x45, 0x5f, 0x49, 0x4d, 0x4d, 0x45, 0x44, 0x49, 0x41, 0x54, 0x45, 0x4c, 0x59, 0x10, 0x01, 0x22,
	0xee, 0x03, 0x0a, 0x08, 0x55, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x12, 0x17, 0x0a, 0x07,
	0x73, 0x79, 0x6e, 0x63, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x04, 0x52, 0x06, 0x73,
	0x79, 0x6e, 0x63, 0x49, 0x64, 0x12, 0x34, 0x0a, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x18, 0x02,
	0x20, 0x03, 0x28, 0x0b, 0x32, 0x1e, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f,
	0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x55, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x2e, 0x45,
	0x6e, 0x74, 0x72, 0x79, 0x52, 0x05, 0x75, 0x73, 0x65, 0x72, 0x73, 0x12, 0x12, 0x0a, 0x04, 0x66,
	0x75, 0x6c, 0x6c, 0x18, 0x03, 0x20, 0x01, 0x28, 0x08, 0x52, 0x04, 0x66, 0x75, 0x6c, 0x6c, 0x1a,
	0x96, 0x02, 0x0a, 0x05, 0x45, 0x6e, 0x74, 0x72, 0x79, 0x12, 0x1a, 0x0a, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x75, 0x73, 0x65,
	0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x70, 0x61, 0x73, 0x73, 0x77, 0x6f, 0x72,
	0x64, 0x12, 0x18, 0x0a, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x08, 0x52, 0x07, 0x65, 0x6e, 0x61, 0x62, 0x6c, 0x65, 0x64, 0x12, 0x24, 0x0a, 0x0e, 0x72,
	0x61, 0x74, 0x65, 0x5f, 0x64, 0x6f, 0x77, 0x6e, 0x5f, 0x6b, 0x62, 0x70, 0x73, 0x18, 0x04, 0x20,
	0x01, 0x28, 0x0d, 0x52, 0x0c, 0x72, 0x61, 0x74, 0x65, 0x44, 0x6f, 0x77, 0x6e, 0x4b, 0x62, 0x70,
	0x73, 0x12, 0x20, 0x0a, 0x0c, 0x72, 0x61, 0x74, 0x65, 0x5f, 0x75, 0x70, 0x5f, 0x6b, 0x62, 0x70,
	0x73, 0x18, 0x05, 0x20, 0x01, 0x28, 0x0d, 0x52, 0x0a, 0x72, 0x61, 0x74, 0x65, 0x55, 0x70, 0x4b,
	0x62, 0x70, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x6c, 0x32, 0x74, 0x70, 0x5f, 0x6d, 0x6f, 0x64, 0x65,
	0x18, 0x06, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6c, 0x32, 0x74, 0x70, 0x4d, 0x6f, 0x64, 0x65,
	0x12, 0x1a, 0x0a, 0x08, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x18, 0x07, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x08, 0x6f, 0x75, 0x74, 0x62, 0x6f, 0x75, 0x6e, 0x64, 0x12, 0x3a, 0x0a, 0x08,
	0x77, 0x67, 0x5f, 0x70, 0x65, 0x65, 0x72, 0x73, 0x18, 0x08, 0x20, 0x03, 0x28, 0x0b, 0x32, 0x1f,
	0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e,
	0x55, 0x73, 0x65, 0x72, 0x53, 0x79, 0x6e, 0x63, 0x2e, 0x57, 0x67, 0x50, 0x65, 0x65, 0x72, 0x52,
	0x07, 0x77, 0x67, 0x50, 0x65, 0x65, 0x72, 0x73, 0x1a, 0x66, 0x0a, 0x06, 0x57, 0x67, 0x50, 0x65,
	0x65, 0x72, 0x12, 0x1d, 0x0a, 0x0a, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x5f, 0x6b, 0x65, 0x79,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x70, 0x75, 0x62, 0x6c, 0x69, 0x63, 0x4b, 0x65,
	0x79, 0x12, 0x23, 0x0a, 0x0d, 0x70, 0x72, 0x65, 0x73, 0x68, 0x61, 0x72, 0x65, 0x64, 0x5f, 0x6b,
	0x65, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c, 0x70, 0x72, 0x65, 0x73, 0x68, 0x61,
	0x72, 0x65, 0x64, 0x4b, 0x65, 0x79, 0x12, 0x18, 0x0a, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73,
	0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x61, 0x64, 0x64, 0x72, 0x65, 0x73, 0x73,
	0x22, 0x40, 0x0a, 0x0a, 0x44, 0x69, 0x73, 0x63, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1a,
	0x0a, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x08, 0x75, 0x73, 0x65, 0x72, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x16, 0x0a, 0x06, 0x72, 0x65,
	0x61, 0x73, 0x6f, 0x6e, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x06, 0x72, 0x65, 0x61, 0x73,
	0x6f, 0x6e, 0x32, 0x52, 0x0a, 0x07, 0x4e, 0x6f, 0x64, 0x65, 0x48, 0x75, 0x62, 0x12, 0x47, 0x0a,
	0x07, 0x43, 0x6f, 0x6e, 0x6e, 0x65, 0x63, 0x74, 0x12, 0x1c, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e,
	0x61, 0x2e, 0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x41, 0x67, 0x65, 0x6e, 0x74, 0x4d,
	0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x1a, 0x1a, 0x2e, 0x61, 0x74, 0x68, 0x65, 0x6e, 0x61, 0x2e,
	0x6e, 0x6f, 0x64, 0x65, 0x2e, 0x76, 0x31, 0x2e, 0x48, 0x75, 0x62, 0x4d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x28, 0x01, 0x30, 0x01, 0x42, 0x2a, 0x5a, 0x28, 0x67, 0x69, 0x74, 0x68, 0x75, 0x62,
	0x2e, 0x63, 0x6f, 0x6d, 0x2f, 0x41, 0x52, 0x4e, 0x30, 0x59, 0x2f, 0x41, 0x74, 0x68, 0x65, 0x6e,
	0x61, 0x50, 0x61, 0x6e, 0x65, 0x6c, 0x2f, 0x61, 0x67, 0x65, 0x6e, 0x74, 0x2f, 0x70, 0x62, 0x3b,
	0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_athena_node_v1_nodehub_proto_rawDescOnce sync.Once
	file_athena_node_v1_nodehub_proto_rawDescData = file_athena_node_v1_nodehub_proto_rawDesc
)

func file_athena_node_v1_nodehub_proto_rawDescGZIP() []byte {
	file_athena_node_v1_nodehub_proto_rawDescOnce.Do(func() {
		file_athena_node_v1_nodehub_proto_rawDescData = protoimpl.X.CompressGZIP(file_athena_node_v1_nodehub_proto_rawDescData)
	})
	return file_athena_node_v1_nodehub_proto_rawDescData
}

var file_athena_node_v1_nodehub_proto_enumTypes = make([]protoimpl.EnumInfo, 2)
var file_athena_node_v1_nodehub_proto_msgTypes = make([]protoimpl.MessageInfo, 16)
var file_athena_node_v1_nodehub_proto_goTypes = []any{
	(CreditRequest_Reason)(0),      // 0: athena.node.v1.CreditRequest.Reason
	(CreditGrant_FailureAction)(0), // 1: athena.node.v1.CreditGrant.FailureAction
	(*AgentMessage)(nil),           // 2: athena.node.v1.AgentMessage
	(*Hello)(nil),                  // 3: athena.node.v1.Hello
	(*Report)(nil),                 // 4: athena.node.v1.Report
	(*Host)(nil),                   // 5: athena.node.v1.Host
	(*PppSession)(nil),             // 6: athena.node.v1.PppSession
	(*WgPeer)(nil),                 // 7: athena.node.v1.WgPeer
	(*CreditRequest)(nil),          // 8: athena.node.v1.CreditRequest
	(*SyncAck)(nil),                // 9: athena.node.v1.SyncAck
	(*HubMessage)(nil),             // 10: athena.node.v1.HubMessage
	(*Welcome)(nil),                // 11: athena.node.v1.Welcome
	(*Ack)(nil),                    // 12: athena.node.v1.Ack
	(*CreditGrant)(nil),            // 13: athena.node.v1.CreditGrant
	(*UserSync)(nil),               // 14: athena.node.v1.UserSync
	(*Disconnect)(nil),             // 15: athena.node.v1.Disconnect
	(*UserSync_Entry)(nil),         // 16: athena.node.v1.UserSync.Entry
	(*UserSync_WgPeer)(nil),        // 17: athena.node.v1.UserSync.WgPeer
}
var file_athena_node_v1_nodehub_proto_depIdxs = []int32{
	3,  // 0: athena.node.v1.AgentMessage.hello:type_name -> athena.node.v1.Hello
	4,  // 1: athena.node.v1.AgentMessage.report:type_name -> athena.node.v1.Report
	8,  // 2: athena.node.v1.AgentMessage.credit_request:type_name -> athena.node.v1.CreditRequest
	9,  // 3: athena.node.v1.AgentMessage.sync_ack:type_name -> athena.node.v1.SyncAck
	5,  // 4: athena.node.v1.Report.host:type_name -> athena.node.v1.Host
	6,  // 5: athena.node.v1.Report.ppp:type_name -> athena.node.v1.PppSession
	7,  // 6: athena.node.v1.Report.wg:type_name -> athena.node.v1.WgPeer
	0,  // 7: athena.node.v1.CreditRequest.reason:type_name -> athena.node.v1.CreditRequest.Reason
	11, // 8: athena.node.v1.HubMessage.welcome:type_name -> athena.node.v1.Welcome
	12, // 9: athena.node.v1.HubMessage.ack:type_name -> athena.node.v1.Ack
	13, // 10: athena.node.v1.HubMessage.credit_grant:type_name -> athena.node.v1.CreditGrant
	14, // 11: athena.node.v1.HubMessage.user_sync:type_name -> athena.node.v1.UserSync
	15, // 12: athena.node.v1.HubMessage.disconnect:type_name -> athena.node.v1.Disconnect
	1,  // 13: athena.node.v1.CreditGrant.on_hub_unreachable:type_name -> athena.node.v1.CreditGrant.FailureAction
	16, // 14: athena.node.v1.UserSync.users:type_name -> athena.node.v1.UserSync.Entry
	17, // 15: athena.node.v1.UserSync.Entry.wg_peers:type_name -> athena.node.v1.UserSync.WgPeer
	2,  // 16: athena.node.v1.NodeHub.Connect:input_type -> athena.node.v1.AgentMessage
	10, // 17: athena.node.v1.NodeHub.Connect:output_type -> athena.node.v1.HubMessage
	17, // [17:18] is the sub-list for method output_type
	16, // [16:17] is the sub-list for method input_type
	16, // [16:16] is the sub-list for extension type_name
	16, // [16:16] is the sub-list for extension extendee
	0,  // [0:16] is the sub-list for field type_name
}

func init() { file_athena_node_v1_nodehub_proto_init() }
func file_athena_node_v1_nodehub_proto_init() {
	if File_athena_node_v1_nodehub_proto != nil {
		return
	}
	file_athena_node_v1_nodehub_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentMessage_Hello)(nil),
		(*AgentMessage_Report)(nil),
		(*AgentMessage_CreditRequest)(nil),
		(*AgentMessage_SyncAck)(nil),
	}
	file_athena_node_v1_nodehub_proto_msgTypes[8].OneofWrappers = []any{
		(*HubMessage_Welcome)(nil),
		(*HubMessage_Ack)(nil),
		(*HubMessage_CreditGrant)(nil),
		(*HubMessage_UserSync)(nil),
		(*HubMessage_Disconnect)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_athena_node_v1_nodehub_proto_rawDesc,
			NumEnums:      2,
			NumMessages:   16,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_athena_node_v1_nodehub_proto_goTypes,
		DependencyIndexes: file_athena_node_v1_nodehub_proto_depIdxs,
		EnumInfos:         file_athena_node_v1_nodehub_proto_enumTypes,
		MessageInfos:      file_athena_node_v1_nodehub_proto_msgTypes,
	}.Build()
	File_athena_node_v1_nodehub_proto = out.File
	file_athena_node_v1_nodehub_proto_rawDesc = nil
	file_athena_node_v1_nodehub_proto_goTypes = nil
	file_athena_node_v1_nodehub_proto_depIdxs = nil
}
