// Typed API client with JWT handling.

const TOKEN_KEY = "vpn_panel_token";

/**
 * "Keep me signed in" is the choice between the two stores: sessionStorage is
 * emptied when the tab closes, localStorage is not. Reads check both, and every
 * write clears the other, so a session can never be held in both at once and
 * outlive the choice the operator made.
 */
export function getToken(): string | null {
  return sessionStorage.getItem(TOKEN_KEY) ?? localStorage.getItem(TOKEN_KEY);
}
export function setToken(token: string, persist = true) {
  const store = persist ? localStorage : sessionStorage;
  const other = persist ? sessionStorage : localStorage;
  other.removeItem(TOKEN_KEY);
  store.setItem(TOKEN_KEY, token);
}
export function clearToken() {
  localStorage.removeItem(TOKEN_KEY);
  sessionStorage.removeItem(TOKEN_KEY);
}

export class ApiError extends Error {
  status: number;
  constructor(status: number, message: string) {
    super(message);
    this.status = status;
  }
}

async function request<T>(path: string, options: RequestInit = {}): Promise<T> {
  const token = getToken();
  const headers: Record<string, string> = { ...(options.headers as Record<string, string>) };
  // FormData must set its own Content-Type: the multipart boundary is
  // generated by the browser, and naming the header here would replace it with
  // one that has no boundary, which the server cannot parse.
  const isForm = typeof FormData !== "undefined" && options.body instanceof FormData;
  if (options.body && !isForm && !headers["Content-Type"]) {
    headers["Content-Type"] = "application/json";
  }
  if (token) headers["Authorization"] = `Bearer ${token}`;

  const res = await fetch(path, { ...options, headers });

  if (res.status === 401) {
    clearToken();
    // BASE_URL respects the (possibly secret) path the panel is served under.
    if (!path.includes("/auth/login")) window.location.href = `${import.meta.env.BASE_URL}login`;
    throw new ApiError(401, "Unauthorized");
  }
  if (res.status === 204) return undefined as T;

  let data: unknown = null;
  const text = await res.text();
  if (text) {
    try {
      data = JSON.parse(text);
    } catch {
      data = text;
    }
  }
  if (!res.ok) {
    const detail = (data as { detail?: string })?.detail || res.statusText || "Request failed";
    throw new ApiError(res.status, detail);
  }
  return data as T;
}

// ---- Types ----
export interface User {
  id: number;
  username: string;
  password: string;
  quota_bytes: number;
  used_bytes: number;
  rate_up_kbps: number;
  rate_down_kbps: number;
  is_active: boolean;
  expires_at: string | null;
  created_at: string;
  last_seen: string | null;
  total_sessions: number;
  note: string;
  created_by_admin_id: number | null;
  created_by_username: string;
  is_expired: boolean;
  quota_exceeded: boolean;
  online: boolean;
  sub_token: string;
  outbound: string;
  l2tp_mode: string;   // "ipsec" | "raw"
  node_id: number;
  node_name: string;
  /** Already resolved from this user's node (its external proxy), falling back
   *  to the panel-wide setting. Never the node's own address — that is the
   *  machine abroad, which no customer connects to directly. */
  endpoint_l2tp: string;
  endpoint_l2tp_raw: string;
  endpoint_sstp: string;
  endpoint_wg: string;
}

export interface Me {
  id: number;
  username: string;
  role: "superadmin" | "admin";
  can_create_users: boolean;
  max_users: number;
}

export interface Admin {
  id: number;
  username: string;
  role: "superadmin" | "admin";
  is_active: boolean;
  can_create_users: boolean;
  max_users: number;
  created_at: string;
  last_login: string | null;
  note: string;
  user_count: number;
}

export interface AdminPayload {
  username?: string;
  password?: string;
  role?: string;
  is_active?: boolean;
  can_create_users?: boolean;
  max_users?: number;
  note?: string;
}

export interface Invite {
  id: number;
  token: string;
  role: string;
  can_create_users: boolean;
  max_users: number;
  note: string;
  created_at: string;
  expires_at: string | null;
  used: boolean;
}

export interface InvitePayload {
  role?: string;
  can_create_users?: boolean;
  max_users?: number;
  note?: string;
  expires_in_hours?: number;
}

export interface Session {
  username: string;
  ifname: string;
  ip: string;
  // Which server is terminating this session. Every node has its own ppp0, so
  // this is also what makes a session uniquely identifiable.
  node_id: number;
  node_name: string;
  protocol: string;
  calling_station: string;
  uptime_seconds: number;
  rx_bytes: number;
  tx_bytes: number;
  rx_rate_bps: number;
  tx_rate_bps: number;
  state: string;
}

export interface TopUser {
  username: string;
  used_bytes: number;
  quota_bytes: number;
  online: boolean;
}

export interface QuotaUser {
  username: string;
  used_bytes: number;
  quota_bytes: number;
  percent: number;
  online: boolean;
}

export interface Stats {
  total_users: number;
  active_users: number;
  online_count: number;
  traffic_today_bytes: number;
  traffic_total_bytes: number;
  quota_warnings: number;
  expired_users: number;
  rx_rate_bps: number;
  tx_rate_bps: number;
  top_users: TopUser[];
  near_quota: QuotaUser[];
}

export interface TrafficPoint {
  ts: string;
  online_count: number;
  rx_bps: number;
  tx_bps: number;
}

export interface SystemStats {
  cpu_percent: number;
  mem_total: number;
  mem_used: number;
  mem_percent: number;
  disk_total: number;
  disk_used: number;
  disk_percent: number;
  net_rx_bps: number;
  net_tx_bps: number;
  load_1: number;
  load_5: number;
  load_15: number;
  uptime_seconds: number;
  hostname: string;
  kernel: string;
}

export interface ConnEvent {
  ts: string;
  username: string;
  in_octets: number;
  out_octets: number;
  total_octets: number;
  session_time: number;
}

export interface AuditEntry {
  id: number;
  ts: string;
  actor: string;
  action: string;
  target: string;
  detail: string;
}

export interface Health {
  status: string;
  xl2tpd: boolean;
  ipsec: boolean;
  db: boolean;
  accounting_log: boolean;
  uptime_seconds: number;
}

export interface ServerSettings {
  vpn_psk: string;
  wan_iface: string;
  ppp_local_ip: string;
  ppp_pool: string;
  admin_username: string;
  chap_secrets: string;
  server_address: string;
  sstp_address: string;
  sub_address: string;
  l2tp_raw_address: string;
  l2tp_enabled: boolean;
  sstp_enabled: boolean;
}

export interface PanelSettingsPayload {
  server_address?: string;
  sstp_address?: string;
  sub_address?: string;
  l2tp_raw_address?: string;
  l2tp_enabled?: boolean;
  sstp_enabled?: boolean;
}

export interface UserPayload {
  username?: string;
  password?: string;
  quota_bytes?: number;
  rate_up_kbps?: number;
  rate_down_kbps?: number;
  is_active?: boolean;
  expires_at?: string | null;
  note?: string;
  outbound?: string;
  l2tp_mode?: string;
  node_id?: number;
  /** Superadmin only — which operator owns this account. */
  owner_admin_id?: number;
}

export interface OutboundStatus {
  id: string;
  name: string;
  kind: string;
  description: string;
  status: "up" | "down" | "disabled";
  egress_ip: string | null;
  users: number;
  active: number | null;   // live IPs currently routed, null for direct
  is_default: boolean;
  removable?: boolean;     // false for the built-in direct / warp
  country?: string;        // ISO alpha-2, "" for no flag
  endpoint?: string;
  mtu?: number;
  created_at?: string | null;
}

export interface OutboundCreated {
  name: string;
  /** The command to run on the egress server. Contains the pre-shared key. */
  install_command: string;
  expects: string;
}

export interface WgStatus {
  enabled: boolean;
  user_id?: number;
  public_key?: string;
  address?: string;
  online?: boolean;
  created_at?: string;
}

export interface WgConfig {
  config: string;
  qr_svg: string;
  address: string;
  filename: string;
}

export interface BackupInfo {
  name: string;
  size: number;
  created_at: string;
}

export interface BackupList {
  backups: BackupInfo[];
  keep: number;
  dir: string;
}

export type BulkActionType = "enable" | "disable" | "delete" | "reset-quota" | "assign";

/** Login-page appearance. Served without a token — cosmetic values only. */
export interface Branding {
  brand_name: string;
  login_tagline: string;
  login_layout: "split-right" | "split-left" | "centered" | "backdrop";
  login_focal: "center" | "top" | "bottom" | "left" | "right";
  login_overlay: number;
  login_image_url: string;
  has_image: boolean;
  login_image_version: string;
}

export interface BrandingPayload {
  brand_name?: string;
  login_tagline?: string;
  login_layout?: string;
  login_focal?: string;
  login_overlay?: number;
  login_image_url?: string;
}

/**
 * The artwork's URL. The version stamp is what lets the response be cached
 * forever: replacing the image changes the stamp, which changes the URL.
 */
export function brandingImageUrl(b: Branding | undefined | null): string {
  if (!b?.has_image) return "";
  if (b.login_image_url) return b.login_image_url;
  return `/api/branding/image?v=${encodeURIComponent(b.login_image_version)}`;
}

// ---- Endpoints ----
export interface NodeInfo {
  id: number;
  name: string;
  is_local: boolean;
  enabled: boolean;
  address: string;
  note: string;
  agent_version: string;
  hostname: string;
  kernel: string;
  online: boolean;
  last_seen_seconds: number | null;
  sessions: number;
  ppp_count: number;
  wg_count: number;
  uptime_seconds: number;
  load1: number;
  mem_total_bytes: number;
  mem_available_bytes: number;
  xl2tpd_ok: boolean;
  ipsec_ok: boolean;
  accel_ppp_ok: boolean;
  wireguard_ok: boolean;
  rx_total_bytes: number;
  tx_total_bytes: number;
  rx_rate_bps: number;
  tx_rate_bps: number;
  wg_port: number;
  sstp_port: number;
  l2tp_port: number;
  /** What customers dial for this node — the relay in front of it, not the
   *  node's own address. Empty means "use the panel-wide setting". */
  ext_l2tp_address: string;
  ext_l2tp_raw_address: string;
  ext_sstp_address: string;
  ext_wg_endpoint: string;
}

/** Returned once, on registration or rotation. The panel keeps no copy of the
 *  key, so this is the only chance to save it. */
export interface NodeCredentials {
  id: number;
  name: string;
  token: string;
  client_cert: string;
  client_key: string;
  ca_cert: string;
}

export interface NodePayload {
  name?: string;
  address?: string;
  note?: string;
  enabled?: boolean;
  wg_port?: number;
  sstp_port?: number;
  l2tp_port?: number;
  ext_l2tp_address?: string;
  ext_l2tp_raw_address?: string;
  ext_sstp_address?: string;
  ext_wg_endpoint?: string;
}

export const api = {
  login: (username: string, password: string) =>
    request<{ access_token: string; expires_in: number; username: string; role: string }>(
      "/api/auth/login",
      { method: "POST", body: JSON.stringify({ username, password }) },
    ),
  me: () => request<Me>("/api/auth/me"),
  inviteInfo: (token: string) =>
    request<{ role: string; valid: boolean; note: string }>(
      `/api/auth/invite/${encodeURIComponent(token)}`,
    ),
  acceptInvite: (token: string, username: string, password: string) =>
    request<{ access_token: string; expires_in: number; username: string; role: string }>(
      "/api/auth/invite/accept",
      { method: "POST", body: JSON.stringify({ token, username, password }) },
    ),
  changePassword: (current_password: string, new_password: string) =>
    request<{ detail: string }>("/api/auth/change-password", {
      method: "POST",
      body: JSON.stringify({ current_password, new_password }),
    }),

  listUsers: () => request<User[]>("/api/users"),
  getUser: (id: number) => request<User>(`/api/users/${id}`),
  createUser: (p: UserPayload) =>
    request<User>("/api/users", { method: "POST", body: JSON.stringify(p) }),
  updateUser: (id: number, p: UserPayload) =>
    request<User>(`/api/users/${id}`, { method: "PUT", body: JSON.stringify(p) }),
  deleteUser: (id: number) => request<void>(`/api/users/${id}`, { method: "DELETE" }),
  resetQuota: (id: number) => request<User>(`/api/users/${id}/reset-quota`, { method: "POST" }),
  toggleUser: (id: number) => request<User>(`/api/users/${id}/toggle`, { method: "POST" }),
  bulk: (ids: number[], action: BulkActionType, ownerAdminId?: number) =>
    request<{ action: string; affected: string[] }>("/api/users/bulk", {
      method: "POST",
      body: JSON.stringify({ ids, action, owner_admin_id: ownerAdminId }),
    }),

  listSessions: () => request<Session[]>("/api/sessions"),
  disconnect: (username: string) =>
    request<{ detail: string }>(`/api/sessions/${encodeURIComponent(username)}`, {
      method: "DELETE",
    }),

  listAdmins: () => request<Admin[]>("/api/admins"),
  createAdmin: (p: AdminPayload) =>
    request<Admin>("/api/admins", { method: "POST", body: JSON.stringify(p) }),
  updateAdmin: (id: number, p: AdminPayload) =>
    request<Admin>(`/api/admins/${id}`, { method: "PUT", body: JSON.stringify(p) }),
  deleteAdmin: (id: number) => request<void>(`/api/admins/${id}`, { method: "DELETE" }),
  listInvites: () => request<Invite[]>("/api/admins/invites"),
  createInvite: (p: InvitePayload) =>
    request<Invite>("/api/admins/invites", { method: "POST", body: JSON.stringify(p) }),
  revokeInvite: (id: number) =>
    request<void>(`/api/admins/invites/${id}`, { method: "DELETE" }),

  stats: () => request<Stats>("/api/stats"),
  health: () => request<Health>("/api/health"),
  system: () => request<SystemStats>("/api/system"),
  trafficHistory: (minutes = 60) =>
    request<TrafficPoint[]>(`/api/traffic/history?minutes=${minutes}`),
  events: (limit = 200) => request<ConnEvent[]>(`/api/events?limit=${limit}`),
  audit: (limit = 200) => request<AuditEntry[]>(`/api/audit?limit=${limit}`),
  branding: () => request<Branding>("/api/branding"),
  updateBranding: (p: BrandingPayload) =>
    request<Branding>("/api/settings/branding", { method: "PUT", body: JSON.stringify(p) }),
  uploadBrandingImage: (file: File) => {
    const body = new FormData();
    body.append("file", file);
    // No Content-Type here on purpose: the browser has to set the multipart
    // boundary itself, and naming the header would overwrite it with one that
    // has no boundary at all.
    return request<Branding>("/api/settings/branding/image", { method: "POST", body });
  },
  deleteBrandingImage: () =>
    request<Branding>("/api/settings/branding/image", { method: "DELETE" }),

  settings: () => request<ServerSettings>("/api/settings"),
  updateSettings: (p: PanelSettingsPayload) =>
    request<ServerSettings>("/api/settings", { method: "PUT", body: JSON.stringify(p) }),
  outbounds: () => request<OutboundStatus[]>("/api/settings/outbounds"),
  outboundCreate: (body: { name: string; country?: string; note?: string; port?: number; mtu?: number }) =>
    request<OutboundCreated>("/api/settings/outbounds", { method: "POST", body: JSON.stringify(body) }),
  outboundUpdate: (name: string, body: { name?: string; country?: string }) =>
    request<{ ok: boolean; name: string; country: string; renamed: boolean }>(
      `/api/settings/outbounds/${encodeURIComponent(name)}`,
      { method: "PATCH", body: JSON.stringify(body) },
    ),
  outboundRegister: (name: string, registration: string) =>
    request<{ ok: boolean; name: string; endpoint: string }>(
      `/api/settings/outbounds/${encodeURIComponent(name)}/register`,
      { method: "POST", body: JSON.stringify({ registration }) },
    ),
  outboundDelete: (name: string) =>
    request<{ ok: boolean; moved_to_direct: number }>(
      `/api/settings/outbounds/${encodeURIComponent(name)}`,
      { method: "DELETE" },
    ),

  wgStatus: (userId: number) => request<WgStatus>(`/api/wireguard/${userId}`),
  wgEnable: (userId: number) => request<WgStatus>(`/api/wireguard/${userId}/enable`, { method: "POST" }),
  wgDisable: (userId: number) => request<void>(`/api/wireguard/${userId}`, { method: "DELETE" }),
  wgConfig: (userId: number) => request<WgConfig>(`/api/wireguard/${userId}/config`),

  listBackups: () => request<BackupList>("/api/backups"),
  createBackup: () => request<BackupInfo>("/api/backups", { method: "POST" }),
  deleteBackup: (name: string) =>
    request<void>(`/api/backups/${encodeURIComponent(name)}`, { method: "DELETE" }),
  telegramLink: () => request<{ linked: boolean; chat_id: string }>("/api/backups/telegram/test", { method: "POST" }),
  telegramSend: (name: string) =>
    request<{ sent: boolean }>(`/api/backups/${encodeURIComponent(name)}/telegram`, { method: "POST" }),
  downloadBackup: async (name: string) => {
    const token = getToken();
    const res = await fetch(`/api/backups/${encodeURIComponent(name)}/download`, {
      headers: token ? { Authorization: `Bearer ${token}` } : {},
    });
    if (!res.ok) throw new ApiError(res.status, "Download failed");
    const blob = await res.blob();
    const url = URL.createObjectURL(blob);
    const a = document.createElement("a");
    a.href = url;
    a.download = name;
    document.body.appendChild(a);
    a.click();
    a.remove();
    URL.revokeObjectURL(url);
  },

  listNodes: () => request<NodeInfo[]>("/api/nodes"),
  createNode: (p: NodePayload) =>
    request<NodeCredentials>("/api/nodes", { method: "POST", body: JSON.stringify(p) }),
  updateNode: (id: number, p: NodePayload) =>
    request<NodeInfo>(`/api/nodes/${id}`, { method: "PATCH", body: JSON.stringify(p) }),
  rotateNode: (id: number) =>
    request<NodeCredentials>(`/api/nodes/${id}/rotate`, { method: "POST" }),
  reconnectNode: (id: number) =>
    request<{ detail: string }>(`/api/nodes/${id}/reconnect`, { method: "POST" }),
  deleteNode: (id: number) => request<void>(`/api/nodes/${id}`, { method: "DELETE" }),
};
